# coding: utf-8

"""
Slurm REST API

API to access and control Slurm

The version of the OpenAPI document: Slurm-24.11.6&openapi/slurmdbd&openapi/slurmctld
Contact: sales@schedmd.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_accruing import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxAccruing,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_active_jobs import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxActiveJobs,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_jobs import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobs,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_tres import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxTres,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_wall_clock import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxWallClock,
)
from typing import Set
from typing_extensions import Self


class V0041OpenapiSlurmdbdQosRespQosInnerLimitsMax(BaseModel):
    """
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMax
    """  # noqa: E501

    active_jobs: Optional[V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxActiveJobs] = None
    tres: Optional[V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxTres] = None
    wall_clock: Optional[V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxWallClock] = None
    jobs: Optional[V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobs] = None
    accruing: Optional[V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxAccruing] = None
    __properties: ClassVar[List[str]] = [
        "active_jobs",
        "tres",
        "wall_clock",
        "jobs",
        "accruing",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V0041OpenapiSlurmdbdQosRespQosInnerLimitsMax from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of active_jobs
        if self.active_jobs:
            _dict["active_jobs"] = self.active_jobs.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tres
        if self.tres:
            _dict["tres"] = self.tres.to_dict()
        # override the default output from pydantic by calling `to_dict()` of wall_clock
        if self.wall_clock:
            _dict["wall_clock"] = self.wall_clock.to_dict()
        # override the default output from pydantic by calling `to_dict()` of jobs
        if self.jobs:
            _dict["jobs"] = self.jobs.to_dict()
        # override the default output from pydantic by calling `to_dict()` of accruing
        if self.accruing:
            _dict["accruing"] = self.accruing.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V0041OpenapiSlurmdbdQosRespQosInnerLimitsMax from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "active_jobs": V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxActiveJobs.from_dict(
                    obj["active_jobs"]
                )
                if obj.get("active_jobs") is not None
                else None,
                "tres": V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxTres.from_dict(
                    obj["tres"]
                )
                if obj.get("tres") is not None
                else None,
                "wall_clock": V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxWallClock.from_dict(
                    obj["wall_clock"]
                )
                if obj.get("wall_clock") is not None
                else None,
                "jobs": V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobs.from_dict(
                    obj["jobs"]
                )
                if obj.get("jobs") is not None
                else None,
                "accruing": V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxAccruing.from_dict(
                    obj["accruing"]
                )
                if obj.get("accruing") is not None
                else None,
            }
        )
        return _obj
