# coding: utf-8

# flake8: noqa
"""
Slurm REST API

API to access and control Slurm

The version of the OpenAPI document: Slurm-24.11.6&openapi/slurmdbd&openapi/slurmctld
Contact: sales@schedmd.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from slurpy.v0042.models.account import Account
from slurpy.v0042.models.account_short import AccountShort
from slurpy.v0042.models.accounting import Accounting
from slurpy.v0042.models.accounts_add_cond import AccountsAddCond
from slurpy.v0042.models.acct_gather_energy import AcctGatherEnergy
from slurpy.v0042.models.assoc import Assoc
from slurpy.v0042.models.assoc_rec_set import AssocRecSet
from slurpy.v0042.models.assoc_shares_obj_wrap import AssocSharesObjWrap
from slurpy.v0042.models.assoc_short import AssocShort
from slurpy.v0042.models.bf_exit_fields import BfExitFields
from slurpy.v0042.models.cluster_rec import ClusterRec
from slurpy.v0042.models.controller_ping import ControllerPing
from slurpy.v0042.models.coord import Coord
from slurpy.v0042.models.cron_entry import CronEntry
from slurpy.v0042.models.float64_no_val_struct import Float64NoValStruct
from slurpy.v0042.models.instance import Instance
from slurpy.v0042.models.job import Job
from slurpy.v0042.models.job_alloc_req import JobAllocReq
from slurpy.v0042.models.job_array_response_msg_entry import JobArrayResponseMsgEntry
from slurpy.v0042.models.job_desc_msg import JobDescMsg
from slurpy.v0042.models.job_info import JobInfo
from slurpy.v0042.models.job_res import JobRes
from slurpy.v0042.models.job_res_core import JobResCore
from slurpy.v0042.models.job_res_node import JobResNode
from slurpy.v0042.models.job_res_socket import JobResSocket
from slurpy.v0042.models.job_submit_req import JobSubmitReq
from slurpy.v0042.models.kill_jobs_msg import KillJobsMsg
from slurpy.v0042.models.kill_jobs_resp_job import KillJobsRespJob
from slurpy.v0042.models.license import License
from slurpy.v0042.models.node import Node
from slurpy.v0042.models.open_api_accounts_add_cond_resp import (
    OpenAPIAccountsAddCondResp,
)
from slurpy.v0042.models.open_api_accounts_add_cond_resp_str import (
    OpenAPIAccountsAddCondRespStr,
)
from slurpy.v0042.models.open_api_accounts_removed_resp import (
    OpenAPIAccountsRemovedResp,
)
from slurpy.v0042.models.open_api_accounts_resp import OpenAPIAccountsResp
from slurpy.v0042.models.open_api_assocs_removed_resp import OpenAPIAssocsRemovedResp
from slurpy.v0042.models.open_api_assocs_resp import OpenAPIAssocsResp
from slurpy.v0042.models.open_api_clusters_removed_resp import (
    OpenAPIClustersRemovedResp,
)
from slurpy.v0042.models.open_api_clusters_resp import OpenAPIClustersResp
from slurpy.v0042.models.open_api_diag_resp import OpenAPIDiagResp
from slurpy.v0042.models.open_api_error import OpenAPIError
from slurpy.v0042.models.open_api_instances_resp import OpenAPIInstancesResp
from slurpy.v0042.models.open_api_job_alloc_resp import OpenAPIJobAllocResp
from slurpy.v0042.models.open_api_job_info_resp import OpenAPIJobInfoResp
from slurpy.v0042.models.open_api_job_post_response import OpenAPIJobPostResponse
from slurpy.v0042.models.open_api_job_submit_response import OpenAPIJobSubmitResponse
from slurpy.v0042.models.open_api_kill_job_resp import OpenAPIKillJobResp
from slurpy.v0042.models.open_api_kill_jobs_resp import OpenAPIKillJobsResp
from slurpy.v0042.models.open_api_licenses_resp import OpenAPILicensesResp
from slurpy.v0042.models.open_api_meta import OpenAPIMeta
from slurpy.v0042.models.open_api_nodes_resp import OpenAPINodesResp
from slurpy.v0042.models.open_api_partition_resp import OpenAPIPartitionResp
from slurpy.v0042.models.open_api_ping_array_resp import OpenAPIPingArrayResp
from slurpy.v0042.models.open_api_reservation_resp import OpenAPIReservationResp
from slurpy.v0042.models.open_api_resp import OpenAPIResp
from slurpy.v0042.models.open_api_shares_resp import OpenAPISharesResp
from slurpy.v0042.models.open_api_slurmdbd_config_resp import OpenAPISlurmdbdConfigResp
from slurpy.v0042.models.open_api_slurmdbd_jobs_resp import OpenAPISlurmdbdJobsResp
from slurpy.v0042.models.open_api_slurmdbd_ping_resp import OpenAPISlurmdbdPingResp
from slurpy.v0042.models.open_api_slurmdbd_qos_removed_resp import (
    OpenAPISlurmdbdQosRemovedResp,
)
from slurpy.v0042.models.open_api_slurmdbd_qos_resp import OpenAPISlurmdbdQosResp
from slurpy.v0042.models.open_api_slurmdbd_stats_resp import OpenAPISlurmdbdStatsResp
from slurpy.v0042.models.open_api_tres_resp import OpenAPITresResp
from slurpy.v0042.models.open_api_users_add_cond_resp import OpenAPIUsersAddCondResp
from slurpy.v0042.models.open_api_users_add_cond_resp_str import (
    OpenAPIUsersAddCondRespStr,
)
from slurpy.v0042.models.open_api_users_resp import OpenAPIUsersResp
from slurpy.v0042.models.open_api_warning import OpenAPIWarning
from slurpy.v0042.models.open_api_wckey_removed_resp import OpenAPIWckeyRemovedResp
from slurpy.v0042.models.open_api_wckey_resp import OpenAPIWckeyResp
from slurpy.v0042.models.part_prio import PartPrio
from slurpy.v0042.models.partition_info import PartitionInfo
from slurpy.v0042.models.process_exit_code_verbose import ProcessExitCodeVerbose
from slurpy.v0042.models.qos import Qos
from slurpy.v0042.models.reservation_core_spec import ReservationCoreSpec
from slurpy.v0042.models.reservation_info import ReservationInfo
from slurpy.v0042.models.rollup_stats import RollupStats
from slurpy.v0042.models.schedule_exit_fields import ScheduleExitFields
from slurpy.v0042.models.shares_float128_tres import SharesFloat128Tres
from slurpy.v0042.models.shares_resp_msg import SharesRespMsg
from slurpy.v0042.models.shares_uint64_tres import SharesUint64Tres
from slurpy.v0042.models.slurmdbd_ping import SlurmdbdPing
from slurpy.v0042.models.stats_msg import StatsMsg
from slurpy.v0042.models.stats_msg_rpc_dump import StatsMsgRpcDump
from slurpy.v0042.models.stats_msg_rpc_queue import StatsMsgRpcQueue
from slurpy.v0042.models.stats_msg_rpc_type import StatsMsgRpcType
from slurpy.v0042.models.stats_msg_rpc_user import StatsMsgRpcUser
from slurpy.v0042.models.stats_rec import StatsRec
from slurpy.v0042.models.stats_rpc import StatsRpc
from slurpy.v0042.models.stats_user import StatsUser
from slurpy.v0042.models.step import Step
from slurpy.v0042.models.tres import Tres
from slurpy.v0042.models.uint16_no_val_struct import Uint16NoValStruct
from slurpy.v0042.models.uint32_no_val_struct import Uint32NoValStruct
from slurpy.v0042.models.uint64_no_val_struct import Uint64NoValStruct
from slurpy.v0042.models.update_node_msg import UpdateNodeMsg
from slurpy.v0042.models.user import User
from slurpy.v0042.models.user_short import UserShort
from slurpy.v0042.models.users_add_cond import UsersAddCond
from slurpy.v0042.models.v0042_accounting_allocated import V0042AccountingAllocated
from slurpy.v0042.models.v0042_assoc_default import V0042AssocDefault
from slurpy.v0042.models.v0042_assoc_max import V0042AssocMax
from slurpy.v0042.models.v0042_assoc_max_jobs import V0042AssocMaxJobs
from slurpy.v0042.models.v0042_assoc_max_jobs_per import V0042AssocMaxJobsPer
from slurpy.v0042.models.v0042_assoc_max_per import V0042AssocMaxPer
from slurpy.v0042.models.v0042_assoc_max_per_account import V0042AssocMaxPerAccount
from slurpy.v0042.models.v0042_assoc_max_tres import V0042AssocMaxTres
from slurpy.v0042.models.v0042_assoc_max_tres_group import V0042AssocMaxTresGroup
from slurpy.v0042.models.v0042_assoc_max_tres_minutes import V0042AssocMaxTresMinutes
from slurpy.v0042.models.v0042_assoc_max_tres_per import V0042AssocMaxTresPer
from slurpy.v0042.models.v0042_assoc_min import V0042AssocMin
from slurpy.v0042.models.v0042_assoc_shares_obj_wrap_fairshare import (
    V0042AssocSharesObjWrapFairshare,
)
from slurpy.v0042.models.v0042_assoc_shares_obj_wrap_tres import (
    V0042AssocSharesObjWrapTres,
)
from slurpy.v0042.models.v0042_cluster_rec_associations import (
    V0042ClusterRecAssociations,
)
from slurpy.v0042.models.v0042_cluster_rec_controller import V0042ClusterRecController
from slurpy.v0042.models.v0042_cron_entry_line import V0042CronEntryLine
from slurpy.v0042.models.v0042_instance_time import V0042InstanceTime
from slurpy.v0042.models.v0042_job_array import V0042JobArray
from slurpy.v0042.models.v0042_job_array_limits import V0042JobArrayLimits
from slurpy.v0042.models.v0042_job_array_limits_max import V0042JobArrayLimitsMax
from slurpy.v0042.models.v0042_job_array_limits_max_running import (
    V0042JobArrayLimitsMaxRunning,
)
from slurpy.v0042.models.v0042_job_comment import V0042JobComment
from slurpy.v0042.models.v0042_job_desc_msg_rlimits import V0042JobDescMsgRlimits
from slurpy.v0042.models.v0042_job_het import V0042JobHet
from slurpy.v0042.models.v0042_job_info_power import V0042JobInfoPower
from slurpy.v0042.models.v0042_job_mcs import V0042JobMcs
from slurpy.v0042.models.v0042_job_required import V0042JobRequired
from slurpy.v0042.models.v0042_job_res_node_cpus import V0042JobResNodeCpus
from slurpy.v0042.models.v0042_job_res_node_memory import V0042JobResNodeMemory
from slurpy.v0042.models.v0042_job_res_nodes import V0042JobResNodes
from slurpy.v0042.models.v0042_job_reservation import V0042JobReservation
from slurpy.v0042.models.v0042_job_state import V0042JobState
from slurpy.v0042.models.v0042_job_time import V0042JobTime
from slurpy.v0042.models.v0042_job_time_system import V0042JobTimeSystem
from slurpy.v0042.models.v0042_job_time_total import V0042JobTimeTotal
from slurpy.v0042.models.v0042_job_time_user import V0042JobTimeUser
from slurpy.v0042.models.v0042_job_tres import V0042JobTres
from slurpy.v0042.models.v0042_kill_jobs_resp_job_error import V0042KillJobsRespJobError
from slurpy.v0042.models.v0042_kill_jobs_resp_job_federation import (
    V0042KillJobsRespJobFederation,
)
from slurpy.v0042.models.v0042_openapi_meta_client import V0042OpenapiMetaClient
from slurpy.v0042.models.v0042_openapi_meta_plugin import V0042OpenapiMetaPlugin
from slurpy.v0042.models.v0042_openapi_meta_slurm import V0042OpenapiMetaSlurm
from slurpy.v0042.models.v0042_openapi_meta_slurm_version import (
    V0042OpenapiMetaSlurmVersion,
)
from slurpy.v0042.models.v0042_partition_info_accounts import V0042PartitionInfoAccounts
from slurpy.v0042.models.v0042_partition_info_cpus import V0042PartitionInfoCpus
from slurpy.v0042.models.v0042_partition_info_defaults import V0042PartitionInfoDefaults
from slurpy.v0042.models.v0042_partition_info_groups import V0042PartitionInfoGroups
from slurpy.v0042.models.v0042_partition_info_maximums import V0042PartitionInfoMaximums
from slurpy.v0042.models.v0042_partition_info_maximums_oversubscribe import (
    V0042PartitionInfoMaximumsOversubscribe,
)
from slurpy.v0042.models.v0042_partition_info_minimums import V0042PartitionInfoMinimums
from slurpy.v0042.models.v0042_partition_info_nodes import V0042PartitionInfoNodes
from slurpy.v0042.models.v0042_partition_info_partition import (
    V0042PartitionInfoPartition,
)
from slurpy.v0042.models.v0042_partition_info_priority import V0042PartitionInfoPriority
from slurpy.v0042.models.v0042_partition_info_qos import V0042PartitionInfoQos
from slurpy.v0042.models.v0042_partition_info_timeouts import V0042PartitionInfoTimeouts
from slurpy.v0042.models.v0042_partition_info_tres import V0042PartitionInfoTres
from slurpy.v0042.models.v0042_process_exit_code_verbose_signal import (
    V0042ProcessExitCodeVerboseSignal,
)
from slurpy.v0042.models.v0042_qos_limits import V0042QosLimits
from slurpy.v0042.models.v0042_qos_limits_max import V0042QosLimitsMax
from slurpy.v0042.models.v0042_qos_limits_max_active_jobs import (
    V0042QosLimitsMaxActiveJobs,
)
from slurpy.v0042.models.v0042_qos_limits_max_jobs import V0042QosLimitsMaxJobs
from slurpy.v0042.models.v0042_qos_limits_max_jobs_active_jobs import (
    V0042QosLimitsMaxJobsActiveJobs,
)
from slurpy.v0042.models.v0042_qos_limits_max_jobs_active_jobs_per import (
    V0042QosLimitsMaxJobsActiveJobsPer,
)
from slurpy.v0042.models.v0042_qos_limits_max_tres import V0042QosLimitsMaxTres
from slurpy.v0042.models.v0042_qos_limits_max_tres_minutes import (
    V0042QosLimitsMaxTresMinutes,
)
from slurpy.v0042.models.v0042_qos_limits_max_tres_minutes_per import (
    V0042QosLimitsMaxTresMinutesPer,
)
from slurpy.v0042.models.v0042_qos_limits_max_tres_per import V0042QosLimitsMaxTresPer
from slurpy.v0042.models.v0042_qos_limits_max_wall_clock import (
    V0042QosLimitsMaxWallClock,
)
from slurpy.v0042.models.v0042_qos_limits_max_wall_clock_per import (
    V0042QosLimitsMaxWallClockPer,
)
from slurpy.v0042.models.v0042_qos_limits_min import V0042QosLimitsMin
from slurpy.v0042.models.v0042_qos_limits_min_tres import V0042QosLimitsMinTres
from slurpy.v0042.models.v0042_qos_limits_min_tres_per import V0042QosLimitsMinTresPer
from slurpy.v0042.models.v0042_qos_preempt import V0042QosPreempt
from slurpy.v0042.models.v0042_reservation_info_purge_completed import (
    V0042ReservationInfoPurgeCompleted,
)
from slurpy.v0042.models.v0042_rollup_stats_daily import V0042RollupStatsDaily
from slurpy.v0042.models.v0042_rollup_stats_daily_duration import (
    V0042RollupStatsDailyDuration,
)
from slurpy.v0042.models.v0042_rollup_stats_hourly import V0042RollupStatsHourly
from slurpy.v0042.models.v0042_rollup_stats_hourly_duration import (
    V0042RollupStatsHourlyDuration,
)
from slurpy.v0042.models.v0042_rollup_stats_monthly import V0042RollupStatsMonthly
from slurpy.v0042.models.v0042_rollup_stats_monthly_duration import (
    V0042RollupStatsMonthlyDuration,
)
from slurpy.v0042.models.v0042_stats_rpc_time import V0042StatsRpcTime
from slurpy.v0042.models.v0042_step_cpu import V0042StepCPU
from slurpy.v0042.models.v0042_step_cpu_requested_frequency import (
    V0042StepCPURequestedFrequency,
)
from slurpy.v0042.models.v0042_step_nodes import V0042StepNodes
from slurpy.v0042.models.v0042_step_statistics import V0042StepStatistics
from slurpy.v0042.models.v0042_step_statistics_cpu import V0042StepStatisticsCPU
from slurpy.v0042.models.v0042_step_statistics_energy import V0042StepStatisticsEnergy
from slurpy.v0042.models.v0042_step_step import V0042StepStep
from slurpy.v0042.models.v0042_step_task import V0042StepTask
from slurpy.v0042.models.v0042_step_tasks import V0042StepTasks
from slurpy.v0042.models.v0042_step_time import V0042StepTime
from slurpy.v0042.models.v0042_step_time_system import V0042StepTimeSystem
from slurpy.v0042.models.v0042_step_time_total import V0042StepTimeTotal
from slurpy.v0042.models.v0042_step_time_user import V0042StepTimeUser
from slurpy.v0042.models.v0042_step_tres import V0042StepTres
from slurpy.v0042.models.v0042_step_tres_consumed import V0042StepTresConsumed
from slurpy.v0042.models.v0042_step_tres_requested import V0042StepTresRequested
from slurpy.v0042.models.v0042_user_default import V0042UserDefault
from slurpy.v0042.models.wckey import Wckey
from slurpy.v0042.models.wckey_tag_struct import WckeyTagStruct
