# coding: utf-8

# flake8: noqa

"""
Slurm REST API

API to access and control Slurm

The version of the OpenAPI document: Slurm-24.11.6&openapi/slurmdbd&openapi/slurmctld
Contact: sales@schedmd.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

__version__ = "1.0.0"

# Define package exports
__all__ = [
    "SlurmApi",
    "SlurmdbApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Account",
    "AccountShort",
    "Accounting",
    "AccountsAddCond",
    "AcctGatherEnergy",
    "Assoc",
    "AssocRecSet",
    "AssocSharesObjWrap",
    "AssocShort",
    "BfExitFields",
    "ClusterRec",
    "ControllerPing",
    "Coord",
    "CronEntry",
    "Float64NoValStruct",
    "Instance",
    "Job",
    "JobAllocReq",
    "JobArrayResponseMsgEntry",
    "JobDescMsg",
    "JobInfo",
    "JobRes",
    "JobResCore",
    "JobResNode",
    "JobResSocket",
    "JobSubmitReq",
    "KillJobsMsg",
    "KillJobsRespJob",
    "License",
    "Node",
    "OpenAPIAccountsAddCondResp",
    "OpenAPIAccountsAddCondRespStr",
    "OpenAPIAccountsRemovedResp",
    "OpenAPIAccountsResp",
    "OpenAPIAssocsRemovedResp",
    "OpenAPIAssocsResp",
    "OpenAPIClustersRemovedResp",
    "OpenAPIClustersResp",
    "OpenAPIDiagResp",
    "OpenAPIError",
    "OpenAPIInstancesResp",
    "OpenAPIJobAllocResp",
    "OpenAPIJobInfoResp",
    "OpenAPIJobPostResponse",
    "OpenAPIJobSubmitResponse",
    "OpenAPIKillJobResp",
    "OpenAPIKillJobsResp",
    "OpenAPILicensesResp",
    "OpenAPIMeta",
    "OpenAPINodesResp",
    "OpenAPIPartitionResp",
    "OpenAPIPingArrayResp",
    "OpenAPIReservationResp",
    "OpenAPIResp",
    "OpenAPISharesResp",
    "OpenAPISlurmdbdConfigResp",
    "OpenAPISlurmdbdJobsResp",
    "OpenAPISlurmdbdPingResp",
    "OpenAPISlurmdbdQosRemovedResp",
    "OpenAPISlurmdbdQosResp",
    "OpenAPISlurmdbdStatsResp",
    "OpenAPITresResp",
    "OpenAPIUsersAddCondResp",
    "OpenAPIUsersAddCondRespStr",
    "OpenAPIUsersResp",
    "OpenAPIWarning",
    "OpenAPIWckeyRemovedResp",
    "OpenAPIWckeyResp",
    "PartPrio",
    "PartitionInfo",
    "ProcessExitCodeVerbose",
    "Qos",
    "ReservationCoreSpec",
    "ReservationInfo",
    "RollupStats",
    "ScheduleExitFields",
    "SharesFloat128Tres",
    "SharesRespMsg",
    "SharesUint64Tres",
    "SlurmdbdPing",
    "StatsMsg",
    "StatsMsgRpcDump",
    "StatsMsgRpcQueue",
    "StatsMsgRpcType",
    "StatsMsgRpcUser",
    "StatsRec",
    "StatsRpc",
    "StatsUser",
    "Step",
    "Tres",
    "Uint16NoValStruct",
    "Uint32NoValStruct",
    "Uint64NoValStruct",
    "UpdateNodeMsg",
    "User",
    "UserShort",
    "UsersAddCond",
    "V0042AccountingAllocated",
    "V0042AssocDefault",
    "V0042AssocMax",
    "V0042AssocMaxJobs",
    "V0042AssocMaxJobsPer",
    "V0042AssocMaxPer",
    "V0042AssocMaxPerAccount",
    "V0042AssocMaxTres",
    "V0042AssocMaxTresGroup",
    "V0042AssocMaxTresMinutes",
    "V0042AssocMaxTresPer",
    "V0042AssocMin",
    "V0042AssocSharesObjWrapFairshare",
    "V0042AssocSharesObjWrapTres",
    "V0042ClusterRecAssociations",
    "V0042ClusterRecController",
    "V0042CronEntryLine",
    "V0042InstanceTime",
    "V0042JobArray",
    "V0042JobArrayLimits",
    "V0042JobArrayLimitsMax",
    "V0042JobArrayLimitsMaxRunning",
    "V0042JobComment",
    "V0042JobDescMsgRlimits",
    "V0042JobHet",
    "V0042JobInfoPower",
    "V0042JobMcs",
    "V0042JobRequired",
    "V0042JobResNodeCpus",
    "V0042JobResNodeMemory",
    "V0042JobResNodes",
    "V0042JobReservation",
    "V0042JobState",
    "V0042JobTime",
    "V0042JobTimeSystem",
    "V0042JobTimeTotal",
    "V0042JobTimeUser",
    "V0042JobTres",
    "V0042KillJobsRespJobError",
    "V0042KillJobsRespJobFederation",
    "V0042OpenapiMetaClient",
    "V0042OpenapiMetaPlugin",
    "V0042OpenapiMetaSlurm",
    "V0042OpenapiMetaSlurmVersion",
    "V0042PartitionInfoAccounts",
    "V0042PartitionInfoCpus",
    "V0042PartitionInfoDefaults",
    "V0042PartitionInfoGroups",
    "V0042PartitionInfoMaximums",
    "V0042PartitionInfoMaximumsOversubscribe",
    "V0042PartitionInfoMinimums",
    "V0042PartitionInfoNodes",
    "V0042PartitionInfoPartition",
    "V0042PartitionInfoPriority",
    "V0042PartitionInfoQos",
    "V0042PartitionInfoTimeouts",
    "V0042PartitionInfoTres",
    "V0042ProcessExitCodeVerboseSignal",
    "V0042QosLimits",
    "V0042QosLimitsMax",
    "V0042QosLimitsMaxActiveJobs",
    "V0042QosLimitsMaxJobs",
    "V0042QosLimitsMaxJobsActiveJobs",
    "V0042QosLimitsMaxJobsActiveJobsPer",
    "V0042QosLimitsMaxTres",
    "V0042QosLimitsMaxTresMinutes",
    "V0042QosLimitsMaxTresMinutesPer",
    "V0042QosLimitsMaxTresPer",
    "V0042QosLimitsMaxWallClock",
    "V0042QosLimitsMaxWallClockPer",
    "V0042QosLimitsMin",
    "V0042QosLimitsMinTres",
    "V0042QosLimitsMinTresPer",
    "V0042QosPreempt",
    "V0042ReservationInfoPurgeCompleted",
    "V0042RollupStatsDaily",
    "V0042RollupStatsDailyDuration",
    "V0042RollupStatsHourly",
    "V0042RollupStatsHourlyDuration",
    "V0042RollupStatsMonthly",
    "V0042RollupStatsMonthlyDuration",
    "V0042StatsRpcTime",
    "V0042StepCPU",
    "V0042StepCPURequestedFrequency",
    "V0042StepNodes",
    "V0042StepStatistics",
    "V0042StepStatisticsCPU",
    "V0042StepStatisticsEnergy",
    "V0042StepStep",
    "V0042StepTask",
    "V0042StepTasks",
    "V0042StepTime",
    "V0042StepTimeSystem",
    "V0042StepTimeTotal",
    "V0042StepTimeUser",
    "V0042StepTres",
    "V0042StepTresConsumed",
    "V0042StepTresRequested",
    "V0042UserDefault",
    "Wckey",
    "WckeyTagStruct",
]

# import apis into sdk package
from slurpy.v0042.api.slurm_api import SlurmApi as SlurmApi
from slurpy.v0042.api.slurmdb_api import SlurmdbApi as SlurmdbApi

# import ApiClient
from slurpy.v0042.api_response import ApiResponse as ApiResponse
from slurpy.v0042.api_client import ApiClient as ApiClient
from slurpy.v0042.configuration import Configuration as Configuration
from slurpy.v0042.exceptions import OpenApiException as OpenApiException
from slurpy.v0042.exceptions import ApiTypeError as ApiTypeError
from slurpy.v0042.exceptions import ApiValueError as ApiValueError
from slurpy.v0042.exceptions import ApiKeyError as ApiKeyError
from slurpy.v0042.exceptions import ApiAttributeError as ApiAttributeError
from slurpy.v0042.exceptions import ApiException as ApiException

# import models into sdk package
from slurpy.v0042.models.account import Account as Account
from slurpy.v0042.models.account_short import AccountShort as AccountShort
from slurpy.v0042.models.accounting import Accounting as Accounting
from slurpy.v0042.models.accounts_add_cond import AccountsAddCond as AccountsAddCond
from slurpy.v0042.models.acct_gather_energy import AcctGatherEnergy as AcctGatherEnergy
from slurpy.v0042.models.assoc import Assoc as Assoc
from slurpy.v0042.models.assoc_rec_set import AssocRecSet as AssocRecSet
from slurpy.v0042.models.assoc_shares_obj_wrap import (
    AssocSharesObjWrap as AssocSharesObjWrap,
)
from slurpy.v0042.models.assoc_short import AssocShort as AssocShort
from slurpy.v0042.models.bf_exit_fields import BfExitFields as BfExitFields
from slurpy.v0042.models.cluster_rec import ClusterRec as ClusterRec
from slurpy.v0042.models.controller_ping import ControllerPing as ControllerPing
from slurpy.v0042.models.coord import Coord as Coord
from slurpy.v0042.models.cron_entry import CronEntry as CronEntry
from slurpy.v0042.models.float64_no_val_struct import (
    Float64NoValStruct as Float64NoValStruct,
)
from slurpy.v0042.models.instance import Instance as Instance
from slurpy.v0042.models.job import Job as Job
from slurpy.v0042.models.job_alloc_req import JobAllocReq as JobAllocReq
from slurpy.v0042.models.job_array_response_msg_entry import (
    JobArrayResponseMsgEntry as JobArrayResponseMsgEntry,
)
from slurpy.v0042.models.job_desc_msg import JobDescMsg as JobDescMsg
from slurpy.v0042.models.job_info import JobInfo as JobInfo
from slurpy.v0042.models.job_res import JobRes as JobRes
from slurpy.v0042.models.job_res_core import JobResCore as JobResCore
from slurpy.v0042.models.job_res_node import JobResNode as JobResNode
from slurpy.v0042.models.job_res_socket import JobResSocket as JobResSocket
from slurpy.v0042.models.job_submit_req import JobSubmitReq as JobSubmitReq
from slurpy.v0042.models.kill_jobs_msg import KillJobsMsg as KillJobsMsg
from slurpy.v0042.models.kill_jobs_resp_job import KillJobsRespJob as KillJobsRespJob
from slurpy.v0042.models.license import License as License
from slurpy.v0042.models.node import Node as Node
from slurpy.v0042.models.open_api_accounts_add_cond_resp import (
    OpenAPIAccountsAddCondResp as OpenAPIAccountsAddCondResp,
)
from slurpy.v0042.models.open_api_accounts_add_cond_resp_str import (
    OpenAPIAccountsAddCondRespStr as OpenAPIAccountsAddCondRespStr,
)
from slurpy.v0042.models.open_api_accounts_removed_resp import (
    OpenAPIAccountsRemovedResp as OpenAPIAccountsRemovedResp,
)
from slurpy.v0042.models.open_api_accounts_resp import (
    OpenAPIAccountsResp as OpenAPIAccountsResp,
)
from slurpy.v0042.models.open_api_assocs_removed_resp import (
    OpenAPIAssocsRemovedResp as OpenAPIAssocsRemovedResp,
)
from slurpy.v0042.models.open_api_assocs_resp import (
    OpenAPIAssocsResp as OpenAPIAssocsResp,
)
from slurpy.v0042.models.open_api_clusters_removed_resp import (
    OpenAPIClustersRemovedResp as OpenAPIClustersRemovedResp,
)
from slurpy.v0042.models.open_api_clusters_resp import (
    OpenAPIClustersResp as OpenAPIClustersResp,
)
from slurpy.v0042.models.open_api_diag_resp import OpenAPIDiagResp as OpenAPIDiagResp
from slurpy.v0042.models.open_api_error import OpenAPIError as OpenAPIError
from slurpy.v0042.models.open_api_instances_resp import (
    OpenAPIInstancesResp as OpenAPIInstancesResp,
)
from slurpy.v0042.models.open_api_job_alloc_resp import (
    OpenAPIJobAllocResp as OpenAPIJobAllocResp,
)
from slurpy.v0042.models.open_api_job_info_resp import (
    OpenAPIJobInfoResp as OpenAPIJobInfoResp,
)
from slurpy.v0042.models.open_api_job_post_response import (
    OpenAPIJobPostResponse as OpenAPIJobPostResponse,
)
from slurpy.v0042.models.open_api_job_submit_response import (
    OpenAPIJobSubmitResponse as OpenAPIJobSubmitResponse,
)
from slurpy.v0042.models.open_api_kill_job_resp import (
    OpenAPIKillJobResp as OpenAPIKillJobResp,
)
from slurpy.v0042.models.open_api_kill_jobs_resp import (
    OpenAPIKillJobsResp as OpenAPIKillJobsResp,
)
from slurpy.v0042.models.open_api_licenses_resp import (
    OpenAPILicensesResp as OpenAPILicensesResp,
)
from slurpy.v0042.models.open_api_meta import OpenAPIMeta as OpenAPIMeta
from slurpy.v0042.models.open_api_nodes_resp import OpenAPINodesResp as OpenAPINodesResp
from slurpy.v0042.models.open_api_partition_resp import (
    OpenAPIPartitionResp as OpenAPIPartitionResp,
)
from slurpy.v0042.models.open_api_ping_array_resp import (
    OpenAPIPingArrayResp as OpenAPIPingArrayResp,
)
from slurpy.v0042.models.open_api_reservation_resp import (
    OpenAPIReservationResp as OpenAPIReservationResp,
)
from slurpy.v0042.models.open_api_resp import OpenAPIResp as OpenAPIResp
from slurpy.v0042.models.open_api_shares_resp import (
    OpenAPISharesResp as OpenAPISharesResp,
)
from slurpy.v0042.models.open_api_slurmdbd_config_resp import (
    OpenAPISlurmdbdConfigResp as OpenAPISlurmdbdConfigResp,
)
from slurpy.v0042.models.open_api_slurmdbd_jobs_resp import (
    OpenAPISlurmdbdJobsResp as OpenAPISlurmdbdJobsResp,
)
from slurpy.v0042.models.open_api_slurmdbd_ping_resp import (
    OpenAPISlurmdbdPingResp as OpenAPISlurmdbdPingResp,
)
from slurpy.v0042.models.open_api_slurmdbd_qos_removed_resp import (
    OpenAPISlurmdbdQosRemovedResp as OpenAPISlurmdbdQosRemovedResp,
)
from slurpy.v0042.models.open_api_slurmdbd_qos_resp import (
    OpenAPISlurmdbdQosResp as OpenAPISlurmdbdQosResp,
)
from slurpy.v0042.models.open_api_slurmdbd_stats_resp import (
    OpenAPISlurmdbdStatsResp as OpenAPISlurmdbdStatsResp,
)
from slurpy.v0042.models.open_api_tres_resp import OpenAPITresResp as OpenAPITresResp
from slurpy.v0042.models.open_api_users_add_cond_resp import (
    OpenAPIUsersAddCondResp as OpenAPIUsersAddCondResp,
)
from slurpy.v0042.models.open_api_users_add_cond_resp_str import (
    OpenAPIUsersAddCondRespStr as OpenAPIUsersAddCondRespStr,
)
from slurpy.v0042.models.open_api_users_resp import OpenAPIUsersResp as OpenAPIUsersResp
from slurpy.v0042.models.open_api_warning import OpenAPIWarning as OpenAPIWarning
from slurpy.v0042.models.open_api_wckey_removed_resp import (
    OpenAPIWckeyRemovedResp as OpenAPIWckeyRemovedResp,
)
from slurpy.v0042.models.open_api_wckey_resp import OpenAPIWckeyResp as OpenAPIWckeyResp
from slurpy.v0042.models.part_prio import PartPrio as PartPrio
from slurpy.v0042.models.partition_info import PartitionInfo as PartitionInfo
from slurpy.v0042.models.process_exit_code_verbose import (
    ProcessExitCodeVerbose as ProcessExitCodeVerbose,
)
from slurpy.v0042.models.qos import Qos as Qos
from slurpy.v0042.models.reservation_core_spec import (
    ReservationCoreSpec as ReservationCoreSpec,
)
from slurpy.v0042.models.reservation_info import ReservationInfo as ReservationInfo
from slurpy.v0042.models.rollup_stats import RollupStats as RollupStats
from slurpy.v0042.models.schedule_exit_fields import (
    ScheduleExitFields as ScheduleExitFields,
)
from slurpy.v0042.models.shares_float128_tres import (
    SharesFloat128Tres as SharesFloat128Tres,
)
from slurpy.v0042.models.shares_resp_msg import SharesRespMsg as SharesRespMsg
from slurpy.v0042.models.shares_uint64_tres import SharesUint64Tres as SharesUint64Tres
from slurpy.v0042.models.slurmdbd_ping import SlurmdbdPing as SlurmdbdPing
from slurpy.v0042.models.stats_msg import StatsMsg as StatsMsg
from slurpy.v0042.models.stats_msg_rpc_dump import StatsMsgRpcDump as StatsMsgRpcDump
from slurpy.v0042.models.stats_msg_rpc_queue import StatsMsgRpcQueue as StatsMsgRpcQueue
from slurpy.v0042.models.stats_msg_rpc_type import StatsMsgRpcType as StatsMsgRpcType
from slurpy.v0042.models.stats_msg_rpc_user import StatsMsgRpcUser as StatsMsgRpcUser
from slurpy.v0042.models.stats_rec import StatsRec as StatsRec
from slurpy.v0042.models.stats_rpc import StatsRpc as StatsRpc
from slurpy.v0042.models.stats_user import StatsUser as StatsUser
from slurpy.v0042.models.step import Step as Step
from slurpy.v0042.models.tres import Tres as Tres
from slurpy.v0042.models.uint16_no_val_struct import (
    Uint16NoValStruct as Uint16NoValStruct,
)
from slurpy.v0042.models.uint32_no_val_struct import (
    Uint32NoValStruct as Uint32NoValStruct,
)
from slurpy.v0042.models.uint64_no_val_struct import (
    Uint64NoValStruct as Uint64NoValStruct,
)
from slurpy.v0042.models.update_node_msg import UpdateNodeMsg as UpdateNodeMsg
from slurpy.v0042.models.user import User as User
from slurpy.v0042.models.user_short import UserShort as UserShort
from slurpy.v0042.models.users_add_cond import UsersAddCond as UsersAddCond
from slurpy.v0042.models.v0042_accounting_allocated import (
    V0042AccountingAllocated as V0042AccountingAllocated,
)
from slurpy.v0042.models.v0042_assoc_default import (
    V0042AssocDefault as V0042AssocDefault,
)
from slurpy.v0042.models.v0042_assoc_max import V0042AssocMax as V0042AssocMax
from slurpy.v0042.models.v0042_assoc_max_jobs import (
    V0042AssocMaxJobs as V0042AssocMaxJobs,
)
from slurpy.v0042.models.v0042_assoc_max_jobs_per import (
    V0042AssocMaxJobsPer as V0042AssocMaxJobsPer,
)
from slurpy.v0042.models.v0042_assoc_max_per import V0042AssocMaxPer as V0042AssocMaxPer
from slurpy.v0042.models.v0042_assoc_max_per_account import (
    V0042AssocMaxPerAccount as V0042AssocMaxPerAccount,
)
from slurpy.v0042.models.v0042_assoc_max_tres import (
    V0042AssocMaxTres as V0042AssocMaxTres,
)
from slurpy.v0042.models.v0042_assoc_max_tres_group import (
    V0042AssocMaxTresGroup as V0042AssocMaxTresGroup,
)
from slurpy.v0042.models.v0042_assoc_max_tres_minutes import (
    V0042AssocMaxTresMinutes as V0042AssocMaxTresMinutes,
)
from slurpy.v0042.models.v0042_assoc_max_tres_per import (
    V0042AssocMaxTresPer as V0042AssocMaxTresPer,
)
from slurpy.v0042.models.v0042_assoc_min import V0042AssocMin as V0042AssocMin
from slurpy.v0042.models.v0042_assoc_shares_obj_wrap_fairshare import (
    V0042AssocSharesObjWrapFairshare as V0042AssocSharesObjWrapFairshare,
)
from slurpy.v0042.models.v0042_assoc_shares_obj_wrap_tres import (
    V0042AssocSharesObjWrapTres as V0042AssocSharesObjWrapTres,
)
from slurpy.v0042.models.v0042_cluster_rec_associations import (
    V0042ClusterRecAssociations as V0042ClusterRecAssociations,
)
from slurpy.v0042.models.v0042_cluster_rec_controller import (
    V0042ClusterRecController as V0042ClusterRecController,
)
from slurpy.v0042.models.v0042_cron_entry_line import (
    V0042CronEntryLine as V0042CronEntryLine,
)
from slurpy.v0042.models.v0042_instance_time import (
    V0042InstanceTime as V0042InstanceTime,
)
from slurpy.v0042.models.v0042_job_array import V0042JobArray as V0042JobArray
from slurpy.v0042.models.v0042_job_array_limits import (
    V0042JobArrayLimits as V0042JobArrayLimits,
)
from slurpy.v0042.models.v0042_job_array_limits_max import (
    V0042JobArrayLimitsMax as V0042JobArrayLimitsMax,
)
from slurpy.v0042.models.v0042_job_array_limits_max_running import (
    V0042JobArrayLimitsMaxRunning as V0042JobArrayLimitsMaxRunning,
)
from slurpy.v0042.models.v0042_job_comment import V0042JobComment as V0042JobComment
from slurpy.v0042.models.v0042_job_desc_msg_rlimits import (
    V0042JobDescMsgRlimits as V0042JobDescMsgRlimits,
)
from slurpy.v0042.models.v0042_job_het import V0042JobHet as V0042JobHet
from slurpy.v0042.models.v0042_job_info_power import (
    V0042JobInfoPower as V0042JobInfoPower,
)
from slurpy.v0042.models.v0042_job_mcs import V0042JobMcs as V0042JobMcs
from slurpy.v0042.models.v0042_job_required import V0042JobRequired as V0042JobRequired
from slurpy.v0042.models.v0042_job_res_node_cpus import (
    V0042JobResNodeCpus as V0042JobResNodeCpus,
)
from slurpy.v0042.models.v0042_job_res_node_memory import (
    V0042JobResNodeMemory as V0042JobResNodeMemory,
)
from slurpy.v0042.models.v0042_job_res_nodes import V0042JobResNodes as V0042JobResNodes
from slurpy.v0042.models.v0042_job_reservation import (
    V0042JobReservation as V0042JobReservation,
)
from slurpy.v0042.models.v0042_job_state import V0042JobState as V0042JobState
from slurpy.v0042.models.v0042_job_time import V0042JobTime as V0042JobTime
from slurpy.v0042.models.v0042_job_time_system import (
    V0042JobTimeSystem as V0042JobTimeSystem,
)
from slurpy.v0042.models.v0042_job_time_total import (
    V0042JobTimeTotal as V0042JobTimeTotal,
)
from slurpy.v0042.models.v0042_job_time_user import V0042JobTimeUser as V0042JobTimeUser
from slurpy.v0042.models.v0042_job_tres import V0042JobTres as V0042JobTres
from slurpy.v0042.models.v0042_kill_jobs_resp_job_error import (
    V0042KillJobsRespJobError as V0042KillJobsRespJobError,
)
from slurpy.v0042.models.v0042_kill_jobs_resp_job_federation import (
    V0042KillJobsRespJobFederation as V0042KillJobsRespJobFederation,
)
from slurpy.v0042.models.v0042_openapi_meta_client import (
    V0042OpenapiMetaClient as V0042OpenapiMetaClient,
)
from slurpy.v0042.models.v0042_openapi_meta_plugin import (
    V0042OpenapiMetaPlugin as V0042OpenapiMetaPlugin,
)
from slurpy.v0042.models.v0042_openapi_meta_slurm import (
    V0042OpenapiMetaSlurm as V0042OpenapiMetaSlurm,
)
from slurpy.v0042.models.v0042_openapi_meta_slurm_version import (
    V0042OpenapiMetaSlurmVersion as V0042OpenapiMetaSlurmVersion,
)
from slurpy.v0042.models.v0042_partition_info_accounts import (
    V0042PartitionInfoAccounts as V0042PartitionInfoAccounts,
)
from slurpy.v0042.models.v0042_partition_info_cpus import (
    V0042PartitionInfoCpus as V0042PartitionInfoCpus,
)
from slurpy.v0042.models.v0042_partition_info_defaults import (
    V0042PartitionInfoDefaults as V0042PartitionInfoDefaults,
)
from slurpy.v0042.models.v0042_partition_info_groups import (
    V0042PartitionInfoGroups as V0042PartitionInfoGroups,
)
from slurpy.v0042.models.v0042_partition_info_maximums import (
    V0042PartitionInfoMaximums as V0042PartitionInfoMaximums,
)
from slurpy.v0042.models.v0042_partition_info_maximums_oversubscribe import (
    V0042PartitionInfoMaximumsOversubscribe as V0042PartitionInfoMaximumsOversubscribe,
)
from slurpy.v0042.models.v0042_partition_info_minimums import (
    V0042PartitionInfoMinimums as V0042PartitionInfoMinimums,
)
from slurpy.v0042.models.v0042_partition_info_nodes import (
    V0042PartitionInfoNodes as V0042PartitionInfoNodes,
)
from slurpy.v0042.models.v0042_partition_info_partition import (
    V0042PartitionInfoPartition as V0042PartitionInfoPartition,
)
from slurpy.v0042.models.v0042_partition_info_priority import (
    V0042PartitionInfoPriority as V0042PartitionInfoPriority,
)
from slurpy.v0042.models.v0042_partition_info_qos import (
    V0042PartitionInfoQos as V0042PartitionInfoQos,
)
from slurpy.v0042.models.v0042_partition_info_timeouts import (
    V0042PartitionInfoTimeouts as V0042PartitionInfoTimeouts,
)
from slurpy.v0042.models.v0042_partition_info_tres import (
    V0042PartitionInfoTres as V0042PartitionInfoTres,
)
from slurpy.v0042.models.v0042_process_exit_code_verbose_signal import (
    V0042ProcessExitCodeVerboseSignal as V0042ProcessExitCodeVerboseSignal,
)
from slurpy.v0042.models.v0042_qos_limits import V0042QosLimits as V0042QosLimits
from slurpy.v0042.models.v0042_qos_limits_max import (
    V0042QosLimitsMax as V0042QosLimitsMax,
)
from slurpy.v0042.models.v0042_qos_limits_max_active_jobs import (
    V0042QosLimitsMaxActiveJobs as V0042QosLimitsMaxActiveJobs,
)
from slurpy.v0042.models.v0042_qos_limits_max_jobs import (
    V0042QosLimitsMaxJobs as V0042QosLimitsMaxJobs,
)
from slurpy.v0042.models.v0042_qos_limits_max_jobs_active_jobs import (
    V0042QosLimitsMaxJobsActiveJobs as V0042QosLimitsMaxJobsActiveJobs,
)
from slurpy.v0042.models.v0042_qos_limits_max_jobs_active_jobs_per import (
    V0042QosLimitsMaxJobsActiveJobsPer as V0042QosLimitsMaxJobsActiveJobsPer,
)
from slurpy.v0042.models.v0042_qos_limits_max_tres import (
    V0042QosLimitsMaxTres as V0042QosLimitsMaxTres,
)
from slurpy.v0042.models.v0042_qos_limits_max_tres_minutes import (
    V0042QosLimitsMaxTresMinutes as V0042QosLimitsMaxTresMinutes,
)
from slurpy.v0042.models.v0042_qos_limits_max_tres_minutes_per import (
    V0042QosLimitsMaxTresMinutesPer as V0042QosLimitsMaxTresMinutesPer,
)
from slurpy.v0042.models.v0042_qos_limits_max_tres_per import (
    V0042QosLimitsMaxTresPer as V0042QosLimitsMaxTresPer,
)
from slurpy.v0042.models.v0042_qos_limits_max_wall_clock import (
    V0042QosLimitsMaxWallClock as V0042QosLimitsMaxWallClock,
)
from slurpy.v0042.models.v0042_qos_limits_max_wall_clock_per import (
    V0042QosLimitsMaxWallClockPer as V0042QosLimitsMaxWallClockPer,
)
from slurpy.v0042.models.v0042_qos_limits_min import (
    V0042QosLimitsMin as V0042QosLimitsMin,
)
from slurpy.v0042.models.v0042_qos_limits_min_tres import (
    V0042QosLimitsMinTres as V0042QosLimitsMinTres,
)
from slurpy.v0042.models.v0042_qos_limits_min_tres_per import (
    V0042QosLimitsMinTresPer as V0042QosLimitsMinTresPer,
)
from slurpy.v0042.models.v0042_qos_preempt import V0042QosPreempt as V0042QosPreempt
from slurpy.v0042.models.v0042_reservation_info_purge_completed import (
    V0042ReservationInfoPurgeCompleted as V0042ReservationInfoPurgeCompleted,
)
from slurpy.v0042.models.v0042_rollup_stats_daily import (
    V0042RollupStatsDaily as V0042RollupStatsDaily,
)
from slurpy.v0042.models.v0042_rollup_stats_daily_duration import (
    V0042RollupStatsDailyDuration as V0042RollupStatsDailyDuration,
)
from slurpy.v0042.models.v0042_rollup_stats_hourly import (
    V0042RollupStatsHourly as V0042RollupStatsHourly,
)
from slurpy.v0042.models.v0042_rollup_stats_hourly_duration import (
    V0042RollupStatsHourlyDuration as V0042RollupStatsHourlyDuration,
)
from slurpy.v0042.models.v0042_rollup_stats_monthly import (
    V0042RollupStatsMonthly as V0042RollupStatsMonthly,
)
from slurpy.v0042.models.v0042_rollup_stats_monthly_duration import (
    V0042RollupStatsMonthlyDuration as V0042RollupStatsMonthlyDuration,
)
from slurpy.v0042.models.v0042_stats_rpc_time import (
    V0042StatsRpcTime as V0042StatsRpcTime,
)
from slurpy.v0042.models.v0042_step_cpu import V0042StepCPU as V0042StepCPU
from slurpy.v0042.models.v0042_step_cpu_requested_frequency import (
    V0042StepCPURequestedFrequency as V0042StepCPURequestedFrequency,
)
from slurpy.v0042.models.v0042_step_nodes import V0042StepNodes as V0042StepNodes
from slurpy.v0042.models.v0042_step_statistics import (
    V0042StepStatistics as V0042StepStatistics,
)
from slurpy.v0042.models.v0042_step_statistics_cpu import (
    V0042StepStatisticsCPU as V0042StepStatisticsCPU,
)
from slurpy.v0042.models.v0042_step_statistics_energy import (
    V0042StepStatisticsEnergy as V0042StepStatisticsEnergy,
)
from slurpy.v0042.models.v0042_step_step import V0042StepStep as V0042StepStep
from slurpy.v0042.models.v0042_step_task import V0042StepTask as V0042StepTask
from slurpy.v0042.models.v0042_step_tasks import V0042StepTasks as V0042StepTasks
from slurpy.v0042.models.v0042_step_time import V0042StepTime as V0042StepTime
from slurpy.v0042.models.v0042_step_time_system import (
    V0042StepTimeSystem as V0042StepTimeSystem,
)
from slurpy.v0042.models.v0042_step_time_total import (
    V0042StepTimeTotal as V0042StepTimeTotal,
)
from slurpy.v0042.models.v0042_step_time_user import (
    V0042StepTimeUser as V0042StepTimeUser,
)
from slurpy.v0042.models.v0042_step_tres import V0042StepTres as V0042StepTres
from slurpy.v0042.models.v0042_step_tres_consumed import (
    V0042StepTresConsumed as V0042StepTresConsumed,
)
from slurpy.v0042.models.v0042_step_tres_requested import (
    V0042StepTresRequested as V0042StepTresRequested,
)
from slurpy.v0042.models.v0042_user_default import V0042UserDefault as V0042UserDefault
from slurpy.v0042.models.wckey import Wckey as Wckey
from slurpy.v0042.models.wckey_tag_struct import WckeyTagStruct as WckeyTagStruct
