# coding: utf-8

# flake8: noqa

"""
Slurm REST API

API to access and control Slurm

The version of the OpenAPI document: Slurm-24.11.6&openapi/slurmdbd&openapi/slurmctld
Contact: sales@schedmd.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

__version__ = "1.0.0"

# Define package exports
__all__ = [
    "SlurmApi",
    "SlurmdbApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "JobAllocReq",
    "JobDescMsg",
    "JobSubmitReq",
    "KillJobsMsg",
    "OpenAPIAccountsAddCondResp",
    "OpenAPIAccountsAddCondRespStr",
    "OpenAPIAccountsRemovedResp",
    "OpenAPIAccountsResp",
    "OpenAPIAssocsRemovedResp",
    "OpenAPIAssocsResp",
    "OpenAPIClustersRemovedResp",
    "OpenAPIClustersResp",
    "OpenAPIDiagResp",
    "OpenAPIInstancesResp",
    "OpenAPIJobAllocResp",
    "OpenAPIJobInfoResp",
    "OpenAPIJobPostResponse",
    "OpenAPIJobSubmitResponse",
    "OpenAPIKillJobsResp",
    "OpenAPILicensesResp",
    "OpenAPINodesResp",
    "OpenAPIPartitionResp",
    "OpenAPIPingArrayResp",
    "OpenAPIReservationResp",
    "OpenAPIResp",
    "OpenAPISharesResp",
    "OpenAPISlurmdbdConfigResp",
    "OpenAPISlurmdbdJobsResp",
    "OpenAPISlurmdbdQosRemovedResp",
    "OpenAPISlurmdbdQosResp",
    "OpenAPISlurmdbdStatsResp",
    "OpenAPITresResp",
    "OpenAPIUsersAddCondResp",
    "OpenAPIUsersAddCondRespStr",
    "OpenAPIUsersResp",
    "OpenAPIWckeyRemovedResp",
    "OpenAPIWckeyResp",
    "UpdateNodeMsg",
    "V0041JobDescMsgBeginTime",
    "V0041JobDescMsgCrontab",
    "V0041JobDescMsgCrontabLine",
    "V0041JobDescMsgDistributionPlaneSize",
    "V0041JobDescMsgKillWarningDelay",
    "V0041JobDescMsgMemoryPerCpu",
    "V0041JobDescMsgPriority",
    "V0041JobDescMsgRequiredSwitches",
    "V0041JobDescMsgRlimits",
    "V0041JobDescMsgRlimitsAs",
    "V0041JobDescMsgRlimitsCore",
    "V0041JobDescMsgRlimitsCpu",
    "V0041JobDescMsgRlimitsData",
    "V0041JobDescMsgRlimitsFsize",
    "V0041JobDescMsgRlimitsMemlock",
    "V0041JobDescMsgRlimitsNofile",
    "V0041JobDescMsgRlimitsNproc",
    "V0041JobDescMsgRlimitsRss",
    "V0041JobDescMsgRlimitsStack",
    "V0041JobDescMsgSegmentSize",
    "V0041JobDescMsgTimeLimit",
    "V0041JobDescMsgTimeMinimum",
    "V0041OpenapiAccountsAddCondRespAccount",
    "V0041OpenapiAccountsAddCondRespAssociationCondition",
    "V0041OpenapiAccountsRespAccountsInner",
    "V0041OpenapiAccountsRespAccountsInnerAssociationsInner",
    "V0041OpenapiAccountsRespAccountsInnerCoordinatorsInner",
    "V0041OpenapiAccountsRespErrorsInner",
    "V0041OpenapiAccountsRespMeta",
    "V0041OpenapiAccountsRespMetaClient",
    "V0041OpenapiAccountsRespMetaPlugin",
    "V0041OpenapiAccountsRespMetaSlurm",
    "V0041OpenapiAccountsRespMetaSlurmVersion",
    "V0041OpenapiAccountsRespWarningsInner",
    "V0041OpenapiClustersRespClustersInner",
    "V0041OpenapiClustersRespClustersInnerAssociations",
    "V0041OpenapiClustersRespClustersInnerAssociationsRoot",
    "V0041OpenapiClustersRespClustersInnerController",
    "V0041OpenapiDiagRespStatistics",
    "V0041OpenapiDiagRespStatisticsBfExit",
    "V0041OpenapiDiagRespStatisticsBfWhenLastCycle",
    "V0041OpenapiDiagRespStatisticsJobStatesTs",
    "V0041OpenapiDiagRespStatisticsPendingRpcsByHostlistInner",
    "V0041OpenapiDiagRespStatisticsPendingRpcsInner",
    "V0041OpenapiDiagRespStatisticsReqTime",
    "V0041OpenapiDiagRespStatisticsReqTimeStart",
    "V0041OpenapiDiagRespStatisticsRpcsByMessageTypeInner",
    "V0041OpenapiDiagRespStatisticsRpcsByMessageTypeInnerAverageTime",
    "V0041OpenapiDiagRespStatisticsRpcsByUserInner",
    "V0041OpenapiDiagRespStatisticsScheduleExit",
    "V0041OpenapiJobInfoRespJobsInner",
    "V0041OpenapiJobInfoRespJobsInnerAccrueTime",
    "V0041OpenapiJobInfoRespJobsInnerArrayJobId",
    "V0041OpenapiJobInfoRespJobsInnerArrayMaxTasks",
    "V0041OpenapiJobInfoRespJobsInnerArrayTaskId",
    "V0041OpenapiJobInfoRespJobsInnerBillableTres",
    "V0041OpenapiJobInfoRespJobsInnerCoresPerSocket",
    "V0041OpenapiJobInfoRespJobsInnerCpuFrequencyGovernor",
    "V0041OpenapiJobInfoRespJobsInnerCpuFrequencyMaximum",
    "V0041OpenapiJobInfoRespJobsInnerCpuFrequencyMinimum",
    "V0041OpenapiJobInfoRespJobsInnerCpus",
    "V0041OpenapiJobInfoRespJobsInnerCpusPerTask",
    "V0041OpenapiJobInfoRespJobsInnerDeadline",
    "V0041OpenapiJobInfoRespJobsInnerDelayBoot",
    "V0041OpenapiJobInfoRespJobsInnerDerivedExitCode",
    "V0041OpenapiJobInfoRespJobsInnerDerivedExitCodeReturnCode",
    "V0041OpenapiJobInfoRespJobsInnerDerivedExitCodeSignal",
    "V0041OpenapiJobInfoRespJobsInnerDerivedExitCodeSignalId",
    "V0041OpenapiJobInfoRespJobsInnerEligibleTime",
    "V0041OpenapiJobInfoRespJobsInnerEndTime",
    "V0041OpenapiJobInfoRespJobsInnerExitCode",
    "V0041OpenapiJobInfoRespJobsInnerHetJobId",
    "V0041OpenapiJobInfoRespJobsInnerHetJobOffset",
    "V0041OpenapiJobInfoRespJobsInnerJobResources",
    "V0041OpenapiJobInfoRespJobsInnerJobResourcesNodes",
    "V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInner",
    "V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerCpus",
    "V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory",
    "V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerSocketsInner",
    "V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerSocketsInnerCoresInner",
    "V0041OpenapiJobInfoRespJobsInnerJobResourcesThreadsPerCore",
    "V0041OpenapiJobInfoRespJobsInnerLastSchedEvaluation",
    "V0041OpenapiJobInfoRespJobsInnerMaxCpus",
    "V0041OpenapiJobInfoRespJobsInnerMaxNodes",
    "V0041OpenapiJobInfoRespJobsInnerMemoryPerNode",
    "V0041OpenapiJobInfoRespJobsInnerMinimumCpusPerNode",
    "V0041OpenapiJobInfoRespJobsInnerMinimumTmpDiskPerNode",
    "V0041OpenapiJobInfoRespJobsInnerNodeCount",
    "V0041OpenapiJobInfoRespJobsInnerPower",
    "V0041OpenapiJobInfoRespJobsInnerPreSusTime",
    "V0041OpenapiJobInfoRespJobsInnerPreemptTime",
    "V0041OpenapiJobInfoRespJobsInnerPreemptableTime",
    "V0041OpenapiJobInfoRespJobsInnerResizeTime",
    "V0041OpenapiJobInfoRespJobsInnerSocketsPerNode",
    "V0041OpenapiJobInfoRespJobsInnerStartTime",
    "V0041OpenapiJobInfoRespJobsInnerSubmitTime",
    "V0041OpenapiJobInfoRespJobsInnerSuspendTime",
    "V0041OpenapiJobInfoRespJobsInnerTasks",
    "V0041OpenapiJobInfoRespJobsInnerTasksPerBoard",
    "V0041OpenapiJobInfoRespJobsInnerTasksPerCore",
    "V0041OpenapiJobInfoRespJobsInnerTasksPerNode",
    "V0041OpenapiJobInfoRespJobsInnerTasksPerSocket",
    "V0041OpenapiJobInfoRespJobsInnerTasksPerTres",
    "V0041OpenapiJobInfoRespJobsInnerThreadsPerCore",
    "V0041OpenapiJobInfoRespLastBackfill",
    "V0041OpenapiJobInfoRespLastUpdate",
    "V0041OpenapiJobPostResponseResultsInner",
    "V0041OpenapiJobSubmitResponseResult",
    "V0041OpenapiKillJobsRespStatusInner",
    "V0041OpenapiKillJobsRespStatusInnerError",
    "V0041OpenapiKillJobsRespStatusInnerFederation",
    "V0041OpenapiKillJobsRespStatusInnerJobId",
    "V0041OpenapiLicensesRespLastUpdate",
    "V0041OpenapiLicensesRespLicensesInner",
    "V0041OpenapiNodesRespLastUpdate",
    "V0041OpenapiNodesRespNodesInner",
    "V0041OpenapiNodesRespNodesInnerBootTime",
    "V0041OpenapiNodesRespNodesInnerEnergy",
    "V0041OpenapiNodesRespNodesInnerEnergyCurrentWatts",
    "V0041OpenapiNodesRespNodesInnerFreeMem",
    "V0041OpenapiNodesRespNodesInnerLastBusy",
    "V0041OpenapiNodesRespNodesInnerReasonChangedAt",
    "V0041OpenapiNodesRespNodesInnerResumeAfter",
    "V0041OpenapiNodesRespNodesInnerSlurmdStartTime",
    "V0041OpenapiPartitionRespLastUpdate",
    "V0041OpenapiPartitionRespPartitionsInner",
    "V0041OpenapiPartitionRespPartitionsInnerAccounts",
    "V0041OpenapiPartitionRespPartitionsInnerCpus",
    "V0041OpenapiPartitionRespPartitionsInnerDefaults",
    "V0041OpenapiPartitionRespPartitionsInnerDefaultsPartitionMemoryPerCpu",
    "V0041OpenapiPartitionRespPartitionsInnerDefaultsPartitionMemoryPerNode",
    "V0041OpenapiPartitionRespPartitionsInnerDefaultsTime",
    "V0041OpenapiPartitionRespPartitionsInnerGroups",
    "V0041OpenapiPartitionRespPartitionsInnerMaximums",
    "V0041OpenapiPartitionRespPartitionsInnerMaximumsCpusPerNode",
    "V0041OpenapiPartitionRespPartitionsInnerMaximumsCpusPerSocket",
    "V0041OpenapiPartitionRespPartitionsInnerMaximumsNodes",
    "V0041OpenapiPartitionRespPartitionsInnerMaximumsOverTimeLimit",
    "V0041OpenapiPartitionRespPartitionsInnerMaximumsOversubscribe",
    "V0041OpenapiPartitionRespPartitionsInnerMaximumsPartitionMemoryPerCpu",
    "V0041OpenapiPartitionRespPartitionsInnerMaximumsPartitionMemoryPerNode",
    "V0041OpenapiPartitionRespPartitionsInnerMaximumsTime",
    "V0041OpenapiPartitionRespPartitionsInnerMinimums",
    "V0041OpenapiPartitionRespPartitionsInnerNodes",
    "V0041OpenapiPartitionRespPartitionsInnerPartition",
    "V0041OpenapiPartitionRespPartitionsInnerPriority",
    "V0041OpenapiPartitionRespPartitionsInnerQos",
    "V0041OpenapiPartitionRespPartitionsInnerSuspendTime",
    "V0041OpenapiPartitionRespPartitionsInnerTimeouts",
    "V0041OpenapiPartitionRespPartitionsInnerTimeoutsResume",
    "V0041OpenapiPartitionRespPartitionsInnerTimeoutsSuspend",
    "V0041OpenapiPartitionRespPartitionsInnerTres",
    "V0041OpenapiPingArrayRespPingsInner",
    "V0041OpenapiReservationRespLastUpdate",
    "V0041OpenapiReservationRespReservationsInner",
    "V0041OpenapiReservationRespReservationsInnerCoreSpecializationsInner",
    "V0041OpenapiReservationRespReservationsInnerEndTime",
    "V0041OpenapiReservationRespReservationsInnerPurgeCompleted",
    "V0041OpenapiReservationRespReservationsInnerPurgeCompletedTime",
    "V0041OpenapiReservationRespReservationsInnerStartTime",
    "V0041OpenapiReservationRespReservationsInnerWatts",
    "V0041OpenapiSharesRespShares",
    "V0041OpenapiSharesRespSharesSharesInner",
    "V0041OpenapiSharesRespSharesSharesInnerFairshare",
    "V0041OpenapiSharesRespSharesSharesInnerShares",
    "V0041OpenapiSharesRespSharesSharesInnerSharesNormalized",
    "V0041OpenapiSharesRespSharesSharesInnerTres",
    "V0041OpenapiSharesRespSharesSharesInnerTresRunSecondsInner",
    "V0041OpenapiSharesRespSharesSharesInnerTresRunSecondsInnerValue",
    "V0041OpenapiSharesRespSharesSharesInnerTresUsageInner",
    "V0041OpenapiSharesRespSharesSharesInnerUsageNormalized",
    "V0041OpenapiSlurmdbdConfigRespAssociationsInner",
    "V0041OpenapiSlurmdbdConfigRespAssociationsInnerDefault",
    "V0041OpenapiSlurmdbdConfigRespAssociationsInnerMax",
    "V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxJobs",
    "V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxJobsAccruing",
    "V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxJobsActive",
    "V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxJobsPer",
    "V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxJobsPerSubmitted",
    "V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxJobsTotal",
    "V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxPer",
    "V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxPerAccount",
    "V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxTres",
    "V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxTresGroup",
    "V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxTresMinutes",
    "V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxTresMinutesPer",
    "V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxTresPer",
    "V0041OpenapiSlurmdbdConfigRespAssociationsInnerMin",
    "V0041OpenapiSlurmdbdConfigRespInstancesInner",
    "V0041OpenapiSlurmdbdConfigRespInstancesInnerTime",
    "V0041OpenapiSlurmdbdJobsRespJobsInner",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerArray",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerArrayLimits",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerArrayLimitsMax",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerArrayLimitsMaxRunning",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerAssociation",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerComment",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerExitCode",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerHet",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerMcs",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerRequired",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerReservation",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerState",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInner",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerCPU",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerCPURequestedFrequency",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerCPURequestedFrequencyMax",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerCPURequestedFrequencyMin",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerNodes",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerStatistics",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerStatisticsCPU",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerStatisticsEnergy",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerStatisticsEnergyConsumed",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerStep",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTask",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTasks",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTime",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeEnd",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeStart",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeSystem",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeTotal",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeUser",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTres",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTresConsumed",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTresRequested",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerTime",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerTimePlanned",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerTimeSystem",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerTimeTotal",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerTimeUser",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerTres",
    "V0041OpenapiSlurmdbdJobsRespJobsInnerWckey",
    "V0041OpenapiSlurmdbdQosRespQosInner",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimits",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsFactor",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMax",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxAccruing",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxAccruingPer",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxAccruingPerAccount",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxAccruingPerUser",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxActiveJobs",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxActiveJobsAccruing",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxActiveJobsCount",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobs",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobsActiveJobs",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobsActiveJobsPer",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobsActiveJobsPerAccount",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobsActiveJobsPerUser",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobsPer",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobsPerAccount",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobsPerUser",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxTres",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxTresMinutes",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxTresMinutesPer",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxTresPer",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxWallClock",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxWallClockPer",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxWallClockPerJob",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxWallClockPerQos",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMin",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMinPriorityThreshold",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMinTres",
    "V0041OpenapiSlurmdbdQosRespQosInnerLimitsMinTresPer",
    "V0041OpenapiSlurmdbdQosRespQosInnerPreempt",
    "V0041OpenapiSlurmdbdQosRespQosInnerPreemptExemptTime",
    "V0041OpenapiSlurmdbdQosRespQosInnerPriority",
    "V0041OpenapiSlurmdbdQosRespQosInnerUsageFactor",
    "V0041OpenapiSlurmdbdQosRespQosInnerUsageThreshold",
    "V0041OpenapiSlurmdbdStatsRespStatistics",
    "V0041OpenapiSlurmdbdStatsRespStatisticsRPCsInner",
    "V0041OpenapiSlurmdbdStatsRespStatisticsRPCsInnerTime",
    "V0041OpenapiSlurmdbdStatsRespStatisticsRollups",
    "V0041OpenapiSlurmdbdStatsRespStatisticsRollupsDaily",
    "V0041OpenapiSlurmdbdStatsRespStatisticsRollupsDailyDuration",
    "V0041OpenapiSlurmdbdStatsRespStatisticsRollupsHourly",
    "V0041OpenapiSlurmdbdStatsRespStatisticsRollupsHourlyDuration",
    "V0041OpenapiSlurmdbdStatsRespStatisticsRollupsMonthly",
    "V0041OpenapiSlurmdbdStatsRespStatisticsRollupsMonthlyDuration",
    "V0041OpenapiSlurmdbdStatsRespStatisticsUsersInner",
    "V0041OpenapiTresRespTRESInner",
    "V0041OpenapiUsersAddCondRespAssociationCondition",
    "V0041OpenapiUsersAddCondRespAssociationConditionAssociation",
    "V0041OpenapiUsersAddCondRespAssociationConditionAssociationGrpjobs",
    "V0041OpenapiUsersAddCondRespAssociationConditionAssociationGrpjobsaccrue",
    "V0041OpenapiUsersAddCondRespAssociationConditionAssociationGrpsubmitjobs",
    "V0041OpenapiUsersAddCondRespAssociationConditionAssociationGrpwall",
    "V0041OpenapiUsersAddCondRespAssociationConditionAssociationMaxjobs",
    "V0041OpenapiUsersAddCondRespAssociationConditionAssociationMaxjobsaccrue",
    "V0041OpenapiUsersAddCondRespAssociationConditionAssociationMaxsubmitjobs",
    "V0041OpenapiUsersAddCondRespAssociationConditionAssociationMaxwalldurationperjob",
    "V0041OpenapiUsersAddCondRespAssociationConditionAssociationMinpriothresh",
    "V0041OpenapiUsersAddCondRespAssociationConditionAssociationPriority",
    "V0041OpenapiUsersAddCondRespUser",
    "V0041OpenapiUsersRespUsersInner",
    "V0041OpenapiUsersRespUsersInnerDefault",
    "V0041OpenapiUsersRespUsersInnerWckeysInner",
    "V0041OpenapiUsersRespUsersInnerWckeysInnerAccountingInner",
    "V0041OpenapiUsersRespUsersInnerWckeysInnerAccountingInnerAllocated",
    "V0041OpenapiUsersRespUsersInnerWckeysInnerAccountingInnerTRES",
    "V0041UpdateNodeMsgResumeAfter",
    "V0041UpdateNodeMsgWeight",
]

# import apis into sdk package
from slurpy.v0041.api.slurm_api import SlurmApi as SlurmApi
from slurpy.v0041.api.slurmdb_api import SlurmdbApi as SlurmdbApi

# import ApiClient
from slurpy.v0041.api_response import ApiResponse as ApiResponse
from slurpy.v0041.api_client import ApiClient as ApiClient
from slurpy.v0041.configuration import Configuration as Configuration
from slurpy.v0041.exceptions import OpenApiException as OpenApiException
from slurpy.v0041.exceptions import ApiTypeError as ApiTypeError
from slurpy.v0041.exceptions import ApiValueError as ApiValueError
from slurpy.v0041.exceptions import ApiKeyError as ApiKeyError
from slurpy.v0041.exceptions import ApiAttributeError as ApiAttributeError
from slurpy.v0041.exceptions import ApiException as ApiException

# import models into sdk package
from slurpy.v0041.models.job_alloc_req import JobAllocReq as JobAllocReq
from slurpy.v0041.models.job_desc_msg import JobDescMsg as JobDescMsg
from slurpy.v0041.models.job_submit_req import JobSubmitReq as JobSubmitReq
from slurpy.v0041.models.kill_jobs_msg import KillJobsMsg as KillJobsMsg
from slurpy.v0041.models.open_api_accounts_add_cond_resp import (
    OpenAPIAccountsAddCondResp as OpenAPIAccountsAddCondResp,
)
from slurpy.v0041.models.open_api_accounts_add_cond_resp_str import (
    OpenAPIAccountsAddCondRespStr as OpenAPIAccountsAddCondRespStr,
)
from slurpy.v0041.models.open_api_accounts_removed_resp import (
    OpenAPIAccountsRemovedResp as OpenAPIAccountsRemovedResp,
)
from slurpy.v0041.models.open_api_accounts_resp import (
    OpenAPIAccountsResp as OpenAPIAccountsResp,
)
from slurpy.v0041.models.open_api_assocs_removed_resp import (
    OpenAPIAssocsRemovedResp as OpenAPIAssocsRemovedResp,
)
from slurpy.v0041.models.open_api_assocs_resp import (
    OpenAPIAssocsResp as OpenAPIAssocsResp,
)
from slurpy.v0041.models.open_api_clusters_removed_resp import (
    OpenAPIClustersRemovedResp as OpenAPIClustersRemovedResp,
)
from slurpy.v0041.models.open_api_clusters_resp import (
    OpenAPIClustersResp as OpenAPIClustersResp,
)
from slurpy.v0041.models.open_api_diag_resp import OpenAPIDiagResp as OpenAPIDiagResp
from slurpy.v0041.models.open_api_instances_resp import (
    OpenAPIInstancesResp as OpenAPIInstancesResp,
)
from slurpy.v0041.models.open_api_job_alloc_resp import (
    OpenAPIJobAllocResp as OpenAPIJobAllocResp,
)
from slurpy.v0041.models.open_api_job_info_resp import (
    OpenAPIJobInfoResp as OpenAPIJobInfoResp,
)
from slurpy.v0041.models.open_api_job_post_response import (
    OpenAPIJobPostResponse as OpenAPIJobPostResponse,
)
from slurpy.v0041.models.open_api_job_submit_response import (
    OpenAPIJobSubmitResponse as OpenAPIJobSubmitResponse,
)
from slurpy.v0041.models.open_api_kill_jobs_resp import (
    OpenAPIKillJobsResp as OpenAPIKillJobsResp,
)
from slurpy.v0041.models.open_api_licenses_resp import (
    OpenAPILicensesResp as OpenAPILicensesResp,
)
from slurpy.v0041.models.open_api_nodes_resp import OpenAPINodesResp as OpenAPINodesResp
from slurpy.v0041.models.open_api_partition_resp import (
    OpenAPIPartitionResp as OpenAPIPartitionResp,
)
from slurpy.v0041.models.open_api_ping_array_resp import (
    OpenAPIPingArrayResp as OpenAPIPingArrayResp,
)
from slurpy.v0041.models.open_api_reservation_resp import (
    OpenAPIReservationResp as OpenAPIReservationResp,
)
from slurpy.v0041.models.open_api_resp import OpenAPIResp as OpenAPIResp
from slurpy.v0041.models.open_api_shares_resp import (
    OpenAPISharesResp as OpenAPISharesResp,
)
from slurpy.v0041.models.open_api_slurmdbd_config_resp import (
    OpenAPISlurmdbdConfigResp as OpenAPISlurmdbdConfigResp,
)
from slurpy.v0041.models.open_api_slurmdbd_jobs_resp import (
    OpenAPISlurmdbdJobsResp as OpenAPISlurmdbdJobsResp,
)
from slurpy.v0041.models.open_api_slurmdbd_qos_removed_resp import (
    OpenAPISlurmdbdQosRemovedResp as OpenAPISlurmdbdQosRemovedResp,
)
from slurpy.v0041.models.open_api_slurmdbd_qos_resp import (
    OpenAPISlurmdbdQosResp as OpenAPISlurmdbdQosResp,
)
from slurpy.v0041.models.open_api_slurmdbd_stats_resp import (
    OpenAPISlurmdbdStatsResp as OpenAPISlurmdbdStatsResp,
)
from slurpy.v0041.models.open_api_tres_resp import OpenAPITresResp as OpenAPITresResp
from slurpy.v0041.models.open_api_users_add_cond_resp import (
    OpenAPIUsersAddCondResp as OpenAPIUsersAddCondResp,
)
from slurpy.v0041.models.open_api_users_add_cond_resp_str import (
    OpenAPIUsersAddCondRespStr as OpenAPIUsersAddCondRespStr,
)
from slurpy.v0041.models.open_api_users_resp import OpenAPIUsersResp as OpenAPIUsersResp
from slurpy.v0041.models.open_api_wckey_removed_resp import (
    OpenAPIWckeyRemovedResp as OpenAPIWckeyRemovedResp,
)
from slurpy.v0041.models.open_api_wckey_resp import OpenAPIWckeyResp as OpenAPIWckeyResp
from slurpy.v0041.models.update_node_msg import UpdateNodeMsg as UpdateNodeMsg
from slurpy.v0041.models.v0041_job_desc_msg_begin_time import (
    V0041JobDescMsgBeginTime as V0041JobDescMsgBeginTime,
)
from slurpy.v0041.models.v0041_job_desc_msg_crontab import (
    V0041JobDescMsgCrontab as V0041JobDescMsgCrontab,
)
from slurpy.v0041.models.v0041_job_desc_msg_crontab_line import (
    V0041JobDescMsgCrontabLine as V0041JobDescMsgCrontabLine,
)
from slurpy.v0041.models.v0041_job_desc_msg_distribution_plane_size import (
    V0041JobDescMsgDistributionPlaneSize as V0041JobDescMsgDistributionPlaneSize,
)
from slurpy.v0041.models.v0041_job_desc_msg_kill_warning_delay import (
    V0041JobDescMsgKillWarningDelay as V0041JobDescMsgKillWarningDelay,
)
from slurpy.v0041.models.v0041_job_desc_msg_memory_per_cpu import (
    V0041JobDescMsgMemoryPerCpu as V0041JobDescMsgMemoryPerCpu,
)
from slurpy.v0041.models.v0041_job_desc_msg_priority import (
    V0041JobDescMsgPriority as V0041JobDescMsgPriority,
)
from slurpy.v0041.models.v0041_job_desc_msg_required_switches import (
    V0041JobDescMsgRequiredSwitches as V0041JobDescMsgRequiredSwitches,
)
from slurpy.v0041.models.v0041_job_desc_msg_rlimits import (
    V0041JobDescMsgRlimits as V0041JobDescMsgRlimits,
)
from slurpy.v0041.models.v0041_job_desc_msg_rlimits_as import (
    V0041JobDescMsgRlimitsAs as V0041JobDescMsgRlimitsAs,
)
from slurpy.v0041.models.v0041_job_desc_msg_rlimits_core import (
    V0041JobDescMsgRlimitsCore as V0041JobDescMsgRlimitsCore,
)
from slurpy.v0041.models.v0041_job_desc_msg_rlimits_cpu import (
    V0041JobDescMsgRlimitsCpu as V0041JobDescMsgRlimitsCpu,
)
from slurpy.v0041.models.v0041_job_desc_msg_rlimits_data import (
    V0041JobDescMsgRlimitsData as V0041JobDescMsgRlimitsData,
)
from slurpy.v0041.models.v0041_job_desc_msg_rlimits_fsize import (
    V0041JobDescMsgRlimitsFsize as V0041JobDescMsgRlimitsFsize,
)
from slurpy.v0041.models.v0041_job_desc_msg_rlimits_memlock import (
    V0041JobDescMsgRlimitsMemlock as V0041JobDescMsgRlimitsMemlock,
)
from slurpy.v0041.models.v0041_job_desc_msg_rlimits_nofile import (
    V0041JobDescMsgRlimitsNofile as V0041JobDescMsgRlimitsNofile,
)
from slurpy.v0041.models.v0041_job_desc_msg_rlimits_nproc import (
    V0041JobDescMsgRlimitsNproc as V0041JobDescMsgRlimitsNproc,
)
from slurpy.v0041.models.v0041_job_desc_msg_rlimits_rss import (
    V0041JobDescMsgRlimitsRss as V0041JobDescMsgRlimitsRss,
)
from slurpy.v0041.models.v0041_job_desc_msg_rlimits_stack import (
    V0041JobDescMsgRlimitsStack as V0041JobDescMsgRlimitsStack,
)
from slurpy.v0041.models.v0041_job_desc_msg_segment_size import (
    V0041JobDescMsgSegmentSize as V0041JobDescMsgSegmentSize,
)
from slurpy.v0041.models.v0041_job_desc_msg_time_limit import (
    V0041JobDescMsgTimeLimit as V0041JobDescMsgTimeLimit,
)
from slurpy.v0041.models.v0041_job_desc_msg_time_minimum import (
    V0041JobDescMsgTimeMinimum as V0041JobDescMsgTimeMinimum,
)
from slurpy.v0041.models.v0041_openapi_accounts_add_cond_resp_account import (
    V0041OpenapiAccountsAddCondRespAccount as V0041OpenapiAccountsAddCondRespAccount,
)
from slurpy.v0041.models.v0041_openapi_accounts_add_cond_resp_association_condition import (
    V0041OpenapiAccountsAddCondRespAssociationCondition as V0041OpenapiAccountsAddCondRespAssociationCondition,
)
from slurpy.v0041.models.v0041_openapi_accounts_resp_accounts_inner import (
    V0041OpenapiAccountsRespAccountsInner as V0041OpenapiAccountsRespAccountsInner,
)
from slurpy.v0041.models.v0041_openapi_accounts_resp_accounts_inner_associations_inner import (
    V0041OpenapiAccountsRespAccountsInnerAssociationsInner as V0041OpenapiAccountsRespAccountsInnerAssociationsInner,
)
from slurpy.v0041.models.v0041_openapi_accounts_resp_accounts_inner_coordinators_inner import (
    V0041OpenapiAccountsRespAccountsInnerCoordinatorsInner as V0041OpenapiAccountsRespAccountsInnerCoordinatorsInner,
)
from slurpy.v0041.models.v0041_openapi_accounts_resp_errors_inner import (
    V0041OpenapiAccountsRespErrorsInner as V0041OpenapiAccountsRespErrorsInner,
)
from slurpy.v0041.models.v0041_openapi_accounts_resp_meta import (
    V0041OpenapiAccountsRespMeta as V0041OpenapiAccountsRespMeta,
)
from slurpy.v0041.models.v0041_openapi_accounts_resp_meta_client import (
    V0041OpenapiAccountsRespMetaClient as V0041OpenapiAccountsRespMetaClient,
)
from slurpy.v0041.models.v0041_openapi_accounts_resp_meta_plugin import (
    V0041OpenapiAccountsRespMetaPlugin as V0041OpenapiAccountsRespMetaPlugin,
)
from slurpy.v0041.models.v0041_openapi_accounts_resp_meta_slurm import (
    V0041OpenapiAccountsRespMetaSlurm as V0041OpenapiAccountsRespMetaSlurm,
)
from slurpy.v0041.models.v0041_openapi_accounts_resp_meta_slurm_version import (
    V0041OpenapiAccountsRespMetaSlurmVersion as V0041OpenapiAccountsRespMetaSlurmVersion,
)
from slurpy.v0041.models.v0041_openapi_accounts_resp_warnings_inner import (
    V0041OpenapiAccountsRespWarningsInner as V0041OpenapiAccountsRespWarningsInner,
)
from slurpy.v0041.models.v0041_openapi_clusters_resp_clusters_inner import (
    V0041OpenapiClustersRespClustersInner as V0041OpenapiClustersRespClustersInner,
)
from slurpy.v0041.models.v0041_openapi_clusters_resp_clusters_inner_associations import (
    V0041OpenapiClustersRespClustersInnerAssociations as V0041OpenapiClustersRespClustersInnerAssociations,
)
from slurpy.v0041.models.v0041_openapi_clusters_resp_clusters_inner_associations_root import (
    V0041OpenapiClustersRespClustersInnerAssociationsRoot as V0041OpenapiClustersRespClustersInnerAssociationsRoot,
)
from slurpy.v0041.models.v0041_openapi_clusters_resp_clusters_inner_controller import (
    V0041OpenapiClustersRespClustersInnerController as V0041OpenapiClustersRespClustersInnerController,
)
from slurpy.v0041.models.v0041_openapi_diag_resp_statistics import (
    V0041OpenapiDiagRespStatistics as V0041OpenapiDiagRespStatistics,
)
from slurpy.v0041.models.v0041_openapi_diag_resp_statistics_bf_exit import (
    V0041OpenapiDiagRespStatisticsBfExit as V0041OpenapiDiagRespStatisticsBfExit,
)
from slurpy.v0041.models.v0041_openapi_diag_resp_statistics_bf_when_last_cycle import (
    V0041OpenapiDiagRespStatisticsBfWhenLastCycle as V0041OpenapiDiagRespStatisticsBfWhenLastCycle,
)
from slurpy.v0041.models.v0041_openapi_diag_resp_statistics_job_states_ts import (
    V0041OpenapiDiagRespStatisticsJobStatesTs as V0041OpenapiDiagRespStatisticsJobStatesTs,
)
from slurpy.v0041.models.v0041_openapi_diag_resp_statistics_pending_rpcs_by_hostlist_inner import (
    V0041OpenapiDiagRespStatisticsPendingRpcsByHostlistInner as V0041OpenapiDiagRespStatisticsPendingRpcsByHostlistInner,
)
from slurpy.v0041.models.v0041_openapi_diag_resp_statistics_pending_rpcs_inner import (
    V0041OpenapiDiagRespStatisticsPendingRpcsInner as V0041OpenapiDiagRespStatisticsPendingRpcsInner,
)
from slurpy.v0041.models.v0041_openapi_diag_resp_statistics_req_time import (
    V0041OpenapiDiagRespStatisticsReqTime as V0041OpenapiDiagRespStatisticsReqTime,
)
from slurpy.v0041.models.v0041_openapi_diag_resp_statistics_req_time_start import (
    V0041OpenapiDiagRespStatisticsReqTimeStart as V0041OpenapiDiagRespStatisticsReqTimeStart,
)
from slurpy.v0041.models.v0041_openapi_diag_resp_statistics_rpcs_by_message_type_inner import (
    V0041OpenapiDiagRespStatisticsRpcsByMessageTypeInner as V0041OpenapiDiagRespStatisticsRpcsByMessageTypeInner,
)
from slurpy.v0041.models.v0041_openapi_diag_resp_statistics_rpcs_by_message_type_inner_average_time import (
    V0041OpenapiDiagRespStatisticsRpcsByMessageTypeInnerAverageTime as V0041OpenapiDiagRespStatisticsRpcsByMessageTypeInnerAverageTime,
)
from slurpy.v0041.models.v0041_openapi_diag_resp_statistics_rpcs_by_user_inner import (
    V0041OpenapiDiagRespStatisticsRpcsByUserInner as V0041OpenapiDiagRespStatisticsRpcsByUserInner,
)
from slurpy.v0041.models.v0041_openapi_diag_resp_statistics_schedule_exit import (
    V0041OpenapiDiagRespStatisticsScheduleExit as V0041OpenapiDiagRespStatisticsScheduleExit,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner import (
    V0041OpenapiJobInfoRespJobsInner as V0041OpenapiJobInfoRespJobsInner,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_accrue_time import (
    V0041OpenapiJobInfoRespJobsInnerAccrueTime as V0041OpenapiJobInfoRespJobsInnerAccrueTime,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_array_job_id import (
    V0041OpenapiJobInfoRespJobsInnerArrayJobId as V0041OpenapiJobInfoRespJobsInnerArrayJobId,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_array_max_tasks import (
    V0041OpenapiJobInfoRespJobsInnerArrayMaxTasks as V0041OpenapiJobInfoRespJobsInnerArrayMaxTasks,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_array_task_id import (
    V0041OpenapiJobInfoRespJobsInnerArrayTaskId as V0041OpenapiJobInfoRespJobsInnerArrayTaskId,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_billable_tres import (
    V0041OpenapiJobInfoRespJobsInnerBillableTres as V0041OpenapiJobInfoRespJobsInnerBillableTres,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_cores_per_socket import (
    V0041OpenapiJobInfoRespJobsInnerCoresPerSocket as V0041OpenapiJobInfoRespJobsInnerCoresPerSocket,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_cpu_frequency_governor import (
    V0041OpenapiJobInfoRespJobsInnerCpuFrequencyGovernor as V0041OpenapiJobInfoRespJobsInnerCpuFrequencyGovernor,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_cpu_frequency_maximum import (
    V0041OpenapiJobInfoRespJobsInnerCpuFrequencyMaximum as V0041OpenapiJobInfoRespJobsInnerCpuFrequencyMaximum,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_cpu_frequency_minimum import (
    V0041OpenapiJobInfoRespJobsInnerCpuFrequencyMinimum as V0041OpenapiJobInfoRespJobsInnerCpuFrequencyMinimum,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_cpus import (
    V0041OpenapiJobInfoRespJobsInnerCpus as V0041OpenapiJobInfoRespJobsInnerCpus,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_cpus_per_task import (
    V0041OpenapiJobInfoRespJobsInnerCpusPerTask as V0041OpenapiJobInfoRespJobsInnerCpusPerTask,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_deadline import (
    V0041OpenapiJobInfoRespJobsInnerDeadline as V0041OpenapiJobInfoRespJobsInnerDeadline,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_delay_boot import (
    V0041OpenapiJobInfoRespJobsInnerDelayBoot as V0041OpenapiJobInfoRespJobsInnerDelayBoot,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_derived_exit_code import (
    V0041OpenapiJobInfoRespJobsInnerDerivedExitCode as V0041OpenapiJobInfoRespJobsInnerDerivedExitCode,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_derived_exit_code_return_code import (
    V0041OpenapiJobInfoRespJobsInnerDerivedExitCodeReturnCode as V0041OpenapiJobInfoRespJobsInnerDerivedExitCodeReturnCode,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_derived_exit_code_signal import (
    V0041OpenapiJobInfoRespJobsInnerDerivedExitCodeSignal as V0041OpenapiJobInfoRespJobsInnerDerivedExitCodeSignal,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_derived_exit_code_signal_id import (
    V0041OpenapiJobInfoRespJobsInnerDerivedExitCodeSignalId as V0041OpenapiJobInfoRespJobsInnerDerivedExitCodeSignalId,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_eligible_time import (
    V0041OpenapiJobInfoRespJobsInnerEligibleTime as V0041OpenapiJobInfoRespJobsInnerEligibleTime,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_end_time import (
    V0041OpenapiJobInfoRespJobsInnerEndTime as V0041OpenapiJobInfoRespJobsInnerEndTime,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_exit_code import (
    V0041OpenapiJobInfoRespJobsInnerExitCode as V0041OpenapiJobInfoRespJobsInnerExitCode,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_het_job_id import (
    V0041OpenapiJobInfoRespJobsInnerHetJobId as V0041OpenapiJobInfoRespJobsInnerHetJobId,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_het_job_offset import (
    V0041OpenapiJobInfoRespJobsInnerHetJobOffset as V0041OpenapiJobInfoRespJobsInnerHetJobOffset,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_job_resources import (
    V0041OpenapiJobInfoRespJobsInnerJobResources as V0041OpenapiJobInfoRespJobsInnerJobResources,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_job_resources_nodes import (
    V0041OpenapiJobInfoRespJobsInnerJobResourcesNodes as V0041OpenapiJobInfoRespJobsInnerJobResourcesNodes,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner import (
    V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInner as V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInner,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_cpus import (
    V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerCpus as V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerCpus,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory import (
    V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory as V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerMemory,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_sockets_inner import (
    V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerSocketsInner as V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerSocketsInner,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_sockets_inner_cores_inner import (
    V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerSocketsInnerCoresInner as V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerSocketsInnerCoresInner,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_job_resources_threads_per_core import (
    V0041OpenapiJobInfoRespJobsInnerJobResourcesThreadsPerCore as V0041OpenapiJobInfoRespJobsInnerJobResourcesThreadsPerCore,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_last_sched_evaluation import (
    V0041OpenapiJobInfoRespJobsInnerLastSchedEvaluation as V0041OpenapiJobInfoRespJobsInnerLastSchedEvaluation,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_max_cpus import (
    V0041OpenapiJobInfoRespJobsInnerMaxCpus as V0041OpenapiJobInfoRespJobsInnerMaxCpus,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_max_nodes import (
    V0041OpenapiJobInfoRespJobsInnerMaxNodes as V0041OpenapiJobInfoRespJobsInnerMaxNodes,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_memory_per_node import (
    V0041OpenapiJobInfoRespJobsInnerMemoryPerNode as V0041OpenapiJobInfoRespJobsInnerMemoryPerNode,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_minimum_cpus_per_node import (
    V0041OpenapiJobInfoRespJobsInnerMinimumCpusPerNode as V0041OpenapiJobInfoRespJobsInnerMinimumCpusPerNode,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_minimum_tmp_disk_per_node import (
    V0041OpenapiJobInfoRespJobsInnerMinimumTmpDiskPerNode as V0041OpenapiJobInfoRespJobsInnerMinimumTmpDiskPerNode,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_node_count import (
    V0041OpenapiJobInfoRespJobsInnerNodeCount as V0041OpenapiJobInfoRespJobsInnerNodeCount,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_power import (
    V0041OpenapiJobInfoRespJobsInnerPower as V0041OpenapiJobInfoRespJobsInnerPower,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_pre_sus_time import (
    V0041OpenapiJobInfoRespJobsInnerPreSusTime as V0041OpenapiJobInfoRespJobsInnerPreSusTime,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_preempt_time import (
    V0041OpenapiJobInfoRespJobsInnerPreemptTime as V0041OpenapiJobInfoRespJobsInnerPreemptTime,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_preemptable_time import (
    V0041OpenapiJobInfoRespJobsInnerPreemptableTime as V0041OpenapiJobInfoRespJobsInnerPreemptableTime,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_resize_time import (
    V0041OpenapiJobInfoRespJobsInnerResizeTime as V0041OpenapiJobInfoRespJobsInnerResizeTime,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_sockets_per_node import (
    V0041OpenapiJobInfoRespJobsInnerSocketsPerNode as V0041OpenapiJobInfoRespJobsInnerSocketsPerNode,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_start_time import (
    V0041OpenapiJobInfoRespJobsInnerStartTime as V0041OpenapiJobInfoRespJobsInnerStartTime,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_submit_time import (
    V0041OpenapiJobInfoRespJobsInnerSubmitTime as V0041OpenapiJobInfoRespJobsInnerSubmitTime,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_suspend_time import (
    V0041OpenapiJobInfoRespJobsInnerSuspendTime as V0041OpenapiJobInfoRespJobsInnerSuspendTime,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_tasks import (
    V0041OpenapiJobInfoRespJobsInnerTasks as V0041OpenapiJobInfoRespJobsInnerTasks,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_tasks_per_board import (
    V0041OpenapiJobInfoRespJobsInnerTasksPerBoard as V0041OpenapiJobInfoRespJobsInnerTasksPerBoard,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_tasks_per_core import (
    V0041OpenapiJobInfoRespJobsInnerTasksPerCore as V0041OpenapiJobInfoRespJobsInnerTasksPerCore,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_tasks_per_node import (
    V0041OpenapiJobInfoRespJobsInnerTasksPerNode as V0041OpenapiJobInfoRespJobsInnerTasksPerNode,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_tasks_per_socket import (
    V0041OpenapiJobInfoRespJobsInnerTasksPerSocket as V0041OpenapiJobInfoRespJobsInnerTasksPerSocket,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_tasks_per_tres import (
    V0041OpenapiJobInfoRespJobsInnerTasksPerTres as V0041OpenapiJobInfoRespJobsInnerTasksPerTres,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_jobs_inner_threads_per_core import (
    V0041OpenapiJobInfoRespJobsInnerThreadsPerCore as V0041OpenapiJobInfoRespJobsInnerThreadsPerCore,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_last_backfill import (
    V0041OpenapiJobInfoRespLastBackfill as V0041OpenapiJobInfoRespLastBackfill,
)
from slurpy.v0041.models.v0041_openapi_job_info_resp_last_update import (
    V0041OpenapiJobInfoRespLastUpdate as V0041OpenapiJobInfoRespLastUpdate,
)
from slurpy.v0041.models.v0041_openapi_job_post_response_results_inner import (
    V0041OpenapiJobPostResponseResultsInner as V0041OpenapiJobPostResponseResultsInner,
)
from slurpy.v0041.models.v0041_openapi_job_submit_response_result import (
    V0041OpenapiJobSubmitResponseResult as V0041OpenapiJobSubmitResponseResult,
)
from slurpy.v0041.models.v0041_openapi_kill_jobs_resp_status_inner import (
    V0041OpenapiKillJobsRespStatusInner as V0041OpenapiKillJobsRespStatusInner,
)
from slurpy.v0041.models.v0041_openapi_kill_jobs_resp_status_inner_error import (
    V0041OpenapiKillJobsRespStatusInnerError as V0041OpenapiKillJobsRespStatusInnerError,
)
from slurpy.v0041.models.v0041_openapi_kill_jobs_resp_status_inner_federation import (
    V0041OpenapiKillJobsRespStatusInnerFederation as V0041OpenapiKillJobsRespStatusInnerFederation,
)
from slurpy.v0041.models.v0041_openapi_kill_jobs_resp_status_inner_job_id import (
    V0041OpenapiKillJobsRespStatusInnerJobId as V0041OpenapiKillJobsRespStatusInnerJobId,
)
from slurpy.v0041.models.v0041_openapi_licenses_resp_last_update import (
    V0041OpenapiLicensesRespLastUpdate as V0041OpenapiLicensesRespLastUpdate,
)
from slurpy.v0041.models.v0041_openapi_licenses_resp_licenses_inner import (
    V0041OpenapiLicensesRespLicensesInner as V0041OpenapiLicensesRespLicensesInner,
)
from slurpy.v0041.models.v0041_openapi_nodes_resp_last_update import (
    V0041OpenapiNodesRespLastUpdate as V0041OpenapiNodesRespLastUpdate,
)
from slurpy.v0041.models.v0041_openapi_nodes_resp_nodes_inner import (
    V0041OpenapiNodesRespNodesInner as V0041OpenapiNodesRespNodesInner,
)
from slurpy.v0041.models.v0041_openapi_nodes_resp_nodes_inner_boot_time import (
    V0041OpenapiNodesRespNodesInnerBootTime as V0041OpenapiNodesRespNodesInnerBootTime,
)
from slurpy.v0041.models.v0041_openapi_nodes_resp_nodes_inner_energy import (
    V0041OpenapiNodesRespNodesInnerEnergy as V0041OpenapiNodesRespNodesInnerEnergy,
)
from slurpy.v0041.models.v0041_openapi_nodes_resp_nodes_inner_energy_current_watts import (
    V0041OpenapiNodesRespNodesInnerEnergyCurrentWatts as V0041OpenapiNodesRespNodesInnerEnergyCurrentWatts,
)
from slurpy.v0041.models.v0041_openapi_nodes_resp_nodes_inner_free_mem import (
    V0041OpenapiNodesRespNodesInnerFreeMem as V0041OpenapiNodesRespNodesInnerFreeMem,
)
from slurpy.v0041.models.v0041_openapi_nodes_resp_nodes_inner_last_busy import (
    V0041OpenapiNodesRespNodesInnerLastBusy as V0041OpenapiNodesRespNodesInnerLastBusy,
)
from slurpy.v0041.models.v0041_openapi_nodes_resp_nodes_inner_reason_changed_at import (
    V0041OpenapiNodesRespNodesInnerReasonChangedAt as V0041OpenapiNodesRespNodesInnerReasonChangedAt,
)
from slurpy.v0041.models.v0041_openapi_nodes_resp_nodes_inner_resume_after import (
    V0041OpenapiNodesRespNodesInnerResumeAfter as V0041OpenapiNodesRespNodesInnerResumeAfter,
)
from slurpy.v0041.models.v0041_openapi_nodes_resp_nodes_inner_slurmd_start_time import (
    V0041OpenapiNodesRespNodesInnerSlurmdStartTime as V0041OpenapiNodesRespNodesInnerSlurmdStartTime,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_last_update import (
    V0041OpenapiPartitionRespLastUpdate as V0041OpenapiPartitionRespLastUpdate,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner import (
    V0041OpenapiPartitionRespPartitionsInner as V0041OpenapiPartitionRespPartitionsInner,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_accounts import (
    V0041OpenapiPartitionRespPartitionsInnerAccounts as V0041OpenapiPartitionRespPartitionsInnerAccounts,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_cpus import (
    V0041OpenapiPartitionRespPartitionsInnerCpus as V0041OpenapiPartitionRespPartitionsInnerCpus,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_defaults import (
    V0041OpenapiPartitionRespPartitionsInnerDefaults as V0041OpenapiPartitionRespPartitionsInnerDefaults,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_defaults_partition_memory_per_cpu import (
    V0041OpenapiPartitionRespPartitionsInnerDefaultsPartitionMemoryPerCpu as V0041OpenapiPartitionRespPartitionsInnerDefaultsPartitionMemoryPerCpu,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_defaults_partition_memory_per_node import (
    V0041OpenapiPartitionRespPartitionsInnerDefaultsPartitionMemoryPerNode as V0041OpenapiPartitionRespPartitionsInnerDefaultsPartitionMemoryPerNode,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_defaults_time import (
    V0041OpenapiPartitionRespPartitionsInnerDefaultsTime as V0041OpenapiPartitionRespPartitionsInnerDefaultsTime,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_groups import (
    V0041OpenapiPartitionRespPartitionsInnerGroups as V0041OpenapiPartitionRespPartitionsInnerGroups,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_maximums import (
    V0041OpenapiPartitionRespPartitionsInnerMaximums as V0041OpenapiPartitionRespPartitionsInnerMaximums,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_maximums_cpus_per_node import (
    V0041OpenapiPartitionRespPartitionsInnerMaximumsCpusPerNode as V0041OpenapiPartitionRespPartitionsInnerMaximumsCpusPerNode,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_maximums_cpus_per_socket import (
    V0041OpenapiPartitionRespPartitionsInnerMaximumsCpusPerSocket as V0041OpenapiPartitionRespPartitionsInnerMaximumsCpusPerSocket,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_maximums_nodes import (
    V0041OpenapiPartitionRespPartitionsInnerMaximumsNodes as V0041OpenapiPartitionRespPartitionsInnerMaximumsNodes,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_maximums_over_time_limit import (
    V0041OpenapiPartitionRespPartitionsInnerMaximumsOverTimeLimit as V0041OpenapiPartitionRespPartitionsInnerMaximumsOverTimeLimit,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_maximums_oversubscribe import (
    V0041OpenapiPartitionRespPartitionsInnerMaximumsOversubscribe as V0041OpenapiPartitionRespPartitionsInnerMaximumsOversubscribe,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_maximums_partition_memory_per_cpu import (
    V0041OpenapiPartitionRespPartitionsInnerMaximumsPartitionMemoryPerCpu as V0041OpenapiPartitionRespPartitionsInnerMaximumsPartitionMemoryPerCpu,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_maximums_partition_memory_per_node import (
    V0041OpenapiPartitionRespPartitionsInnerMaximumsPartitionMemoryPerNode as V0041OpenapiPartitionRespPartitionsInnerMaximumsPartitionMemoryPerNode,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_maximums_time import (
    V0041OpenapiPartitionRespPartitionsInnerMaximumsTime as V0041OpenapiPartitionRespPartitionsInnerMaximumsTime,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_minimums import (
    V0041OpenapiPartitionRespPartitionsInnerMinimums as V0041OpenapiPartitionRespPartitionsInnerMinimums,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_nodes import (
    V0041OpenapiPartitionRespPartitionsInnerNodes as V0041OpenapiPartitionRespPartitionsInnerNodes,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_partition import (
    V0041OpenapiPartitionRespPartitionsInnerPartition as V0041OpenapiPartitionRespPartitionsInnerPartition,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_priority import (
    V0041OpenapiPartitionRespPartitionsInnerPriority as V0041OpenapiPartitionRespPartitionsInnerPriority,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_qos import (
    V0041OpenapiPartitionRespPartitionsInnerQos as V0041OpenapiPartitionRespPartitionsInnerQos,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_suspend_time import (
    V0041OpenapiPartitionRespPartitionsInnerSuspendTime as V0041OpenapiPartitionRespPartitionsInnerSuspendTime,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_timeouts import (
    V0041OpenapiPartitionRespPartitionsInnerTimeouts as V0041OpenapiPartitionRespPartitionsInnerTimeouts,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_timeouts_resume import (
    V0041OpenapiPartitionRespPartitionsInnerTimeoutsResume as V0041OpenapiPartitionRespPartitionsInnerTimeoutsResume,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_timeouts_suspend import (
    V0041OpenapiPartitionRespPartitionsInnerTimeoutsSuspend as V0041OpenapiPartitionRespPartitionsInnerTimeoutsSuspend,
)
from slurpy.v0041.models.v0041_openapi_partition_resp_partitions_inner_tres import (
    V0041OpenapiPartitionRespPartitionsInnerTres as V0041OpenapiPartitionRespPartitionsInnerTres,
)
from slurpy.v0041.models.v0041_openapi_ping_array_resp_pings_inner import (
    V0041OpenapiPingArrayRespPingsInner as V0041OpenapiPingArrayRespPingsInner,
)
from slurpy.v0041.models.v0041_openapi_reservation_resp_last_update import (
    V0041OpenapiReservationRespLastUpdate as V0041OpenapiReservationRespLastUpdate,
)
from slurpy.v0041.models.v0041_openapi_reservation_resp_reservations_inner import (
    V0041OpenapiReservationRespReservationsInner as V0041OpenapiReservationRespReservationsInner,
)
from slurpy.v0041.models.v0041_openapi_reservation_resp_reservations_inner_core_specializations_inner import (
    V0041OpenapiReservationRespReservationsInnerCoreSpecializationsInner as V0041OpenapiReservationRespReservationsInnerCoreSpecializationsInner,
)
from slurpy.v0041.models.v0041_openapi_reservation_resp_reservations_inner_end_time import (
    V0041OpenapiReservationRespReservationsInnerEndTime as V0041OpenapiReservationRespReservationsInnerEndTime,
)
from slurpy.v0041.models.v0041_openapi_reservation_resp_reservations_inner_purge_completed import (
    V0041OpenapiReservationRespReservationsInnerPurgeCompleted as V0041OpenapiReservationRespReservationsInnerPurgeCompleted,
)
from slurpy.v0041.models.v0041_openapi_reservation_resp_reservations_inner_purge_completed_time import (
    V0041OpenapiReservationRespReservationsInnerPurgeCompletedTime as V0041OpenapiReservationRespReservationsInnerPurgeCompletedTime,
)
from slurpy.v0041.models.v0041_openapi_reservation_resp_reservations_inner_start_time import (
    V0041OpenapiReservationRespReservationsInnerStartTime as V0041OpenapiReservationRespReservationsInnerStartTime,
)
from slurpy.v0041.models.v0041_openapi_reservation_resp_reservations_inner_watts import (
    V0041OpenapiReservationRespReservationsInnerWatts as V0041OpenapiReservationRespReservationsInnerWatts,
)
from slurpy.v0041.models.v0041_openapi_shares_resp_shares import (
    V0041OpenapiSharesRespShares as V0041OpenapiSharesRespShares,
)
from slurpy.v0041.models.v0041_openapi_shares_resp_shares_shares_inner import (
    V0041OpenapiSharesRespSharesSharesInner as V0041OpenapiSharesRespSharesSharesInner,
)
from slurpy.v0041.models.v0041_openapi_shares_resp_shares_shares_inner_fairshare import (
    V0041OpenapiSharesRespSharesSharesInnerFairshare as V0041OpenapiSharesRespSharesSharesInnerFairshare,
)
from slurpy.v0041.models.v0041_openapi_shares_resp_shares_shares_inner_shares import (
    V0041OpenapiSharesRespSharesSharesInnerShares as V0041OpenapiSharesRespSharesSharesInnerShares,
)
from slurpy.v0041.models.v0041_openapi_shares_resp_shares_shares_inner_shares_normalized import (
    V0041OpenapiSharesRespSharesSharesInnerSharesNormalized as V0041OpenapiSharesRespSharesSharesInnerSharesNormalized,
)
from slurpy.v0041.models.v0041_openapi_shares_resp_shares_shares_inner_tres import (
    V0041OpenapiSharesRespSharesSharesInnerTres as V0041OpenapiSharesRespSharesSharesInnerTres,
)
from slurpy.v0041.models.v0041_openapi_shares_resp_shares_shares_inner_tres_run_seconds_inner import (
    V0041OpenapiSharesRespSharesSharesInnerTresRunSecondsInner as V0041OpenapiSharesRespSharesSharesInnerTresRunSecondsInner,
)
from slurpy.v0041.models.v0041_openapi_shares_resp_shares_shares_inner_tres_run_seconds_inner_value import (
    V0041OpenapiSharesRespSharesSharesInnerTresRunSecondsInnerValue as V0041OpenapiSharesRespSharesSharesInnerTresRunSecondsInnerValue,
)
from slurpy.v0041.models.v0041_openapi_shares_resp_shares_shares_inner_tres_usage_inner import (
    V0041OpenapiSharesRespSharesSharesInnerTresUsageInner as V0041OpenapiSharesRespSharesSharesInnerTresUsageInner,
)
from slurpy.v0041.models.v0041_openapi_shares_resp_shares_shares_inner_usage_normalized import (
    V0041OpenapiSharesRespSharesSharesInnerUsageNormalized as V0041OpenapiSharesRespSharesSharesInnerUsageNormalized,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_config_resp_associations_inner import (
    V0041OpenapiSlurmdbdConfigRespAssociationsInner as V0041OpenapiSlurmdbdConfigRespAssociationsInner,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_config_resp_associations_inner_default import (
    V0041OpenapiSlurmdbdConfigRespAssociationsInnerDefault as V0041OpenapiSlurmdbdConfigRespAssociationsInnerDefault,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_config_resp_associations_inner_max import (
    V0041OpenapiSlurmdbdConfigRespAssociationsInnerMax as V0041OpenapiSlurmdbdConfigRespAssociationsInnerMax,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_config_resp_associations_inner_max_jobs import (
    V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxJobs as V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxJobs,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_config_resp_associations_inner_max_jobs_accruing import (
    V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxJobsAccruing as V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxJobsAccruing,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_config_resp_associations_inner_max_jobs_active import (
    V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxJobsActive as V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxJobsActive,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_config_resp_associations_inner_max_jobs_per import (
    V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxJobsPer as V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxJobsPer,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_config_resp_associations_inner_max_jobs_per_submitted import (
    V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxJobsPerSubmitted as V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxJobsPerSubmitted,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_config_resp_associations_inner_max_jobs_total import (
    V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxJobsTotal as V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxJobsTotal,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_config_resp_associations_inner_max_per import (
    V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxPer as V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxPer,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_config_resp_associations_inner_max_per_account import (
    V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxPerAccount as V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxPerAccount,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_config_resp_associations_inner_max_tres import (
    V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxTres as V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxTres,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_config_resp_associations_inner_max_tres_group import (
    V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxTresGroup as V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxTresGroup,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_config_resp_associations_inner_max_tres_minutes import (
    V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxTresMinutes as V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxTresMinutes,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_config_resp_associations_inner_max_tres_minutes_per import (
    V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxTresMinutesPer as V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxTresMinutesPer,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_config_resp_associations_inner_max_tres_per import (
    V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxTresPer as V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxTresPer,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_config_resp_associations_inner_min import (
    V0041OpenapiSlurmdbdConfigRespAssociationsInnerMin as V0041OpenapiSlurmdbdConfigRespAssociationsInnerMin,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_config_resp_instances_inner import (
    V0041OpenapiSlurmdbdConfigRespInstancesInner as V0041OpenapiSlurmdbdConfigRespInstancesInner,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_config_resp_instances_inner_time import (
    V0041OpenapiSlurmdbdConfigRespInstancesInnerTime as V0041OpenapiSlurmdbdConfigRespInstancesInnerTime,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner import (
    V0041OpenapiSlurmdbdJobsRespJobsInner as V0041OpenapiSlurmdbdJobsRespJobsInner,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_array import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerArray as V0041OpenapiSlurmdbdJobsRespJobsInnerArray,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_array_limits import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerArrayLimits as V0041OpenapiSlurmdbdJobsRespJobsInnerArrayLimits,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_array_limits_max import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerArrayLimitsMax as V0041OpenapiSlurmdbdJobsRespJobsInnerArrayLimitsMax,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_array_limits_max_running import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerArrayLimitsMaxRunning as V0041OpenapiSlurmdbdJobsRespJobsInnerArrayLimitsMaxRunning,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_association import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerAssociation as V0041OpenapiSlurmdbdJobsRespJobsInnerAssociation,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_comment import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerComment as V0041OpenapiSlurmdbdJobsRespJobsInnerComment,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_exit_code import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerExitCode as V0041OpenapiSlurmdbdJobsRespJobsInnerExitCode,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_het import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerHet as V0041OpenapiSlurmdbdJobsRespJobsInnerHet,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_mcs import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerMcs as V0041OpenapiSlurmdbdJobsRespJobsInnerMcs,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_required import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerRequired as V0041OpenapiSlurmdbdJobsRespJobsInnerRequired,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_reservation import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerReservation as V0041OpenapiSlurmdbdJobsRespJobsInnerReservation,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_state import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerState as V0041OpenapiSlurmdbdJobsRespJobsInnerState,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInner as V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInner,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_cpu import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerCPU as V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerCPU,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_cpu_requested_frequency import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerCPURequestedFrequency as V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerCPURequestedFrequency,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_cpu_requested_frequency_max import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerCPURequestedFrequencyMax as V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerCPURequestedFrequencyMax,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_cpu_requested_frequency_min import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerCPURequestedFrequencyMin as V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerCPURequestedFrequencyMin,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_nodes import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerNodes as V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerNodes,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_statistics import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerStatistics as V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerStatistics,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_statistics_cpu import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerStatisticsCPU as V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerStatisticsCPU,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_statistics_energy import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerStatisticsEnergy as V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerStatisticsEnergy,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_statistics_energy_consumed import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerStatisticsEnergyConsumed as V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerStatisticsEnergyConsumed,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_step import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerStep as V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerStep,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_task import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTask as V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTask,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tasks import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTasks as V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTasks,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTime as V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTime,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_end import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeEnd as V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeEnd,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_start import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeStart as V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeStart,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_system import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeSystem as V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeSystem,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_total import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeTotal as V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeTotal,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_user import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeUser as V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTimeUser,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTres as V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTres,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_consumed import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTresConsumed as V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTresConsumed,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTresRequested as V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTresRequested,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_time import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerTime as V0041OpenapiSlurmdbdJobsRespJobsInnerTime,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_time_planned import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerTimePlanned as V0041OpenapiSlurmdbdJobsRespJobsInnerTimePlanned,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_time_system import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerTimeSystem as V0041OpenapiSlurmdbdJobsRespJobsInnerTimeSystem,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_time_total import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerTimeTotal as V0041OpenapiSlurmdbdJobsRespJobsInnerTimeTotal,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_time_user import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerTimeUser as V0041OpenapiSlurmdbdJobsRespJobsInnerTimeUser,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_tres import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerTres as V0041OpenapiSlurmdbdJobsRespJobsInnerTres,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_wckey import (
    V0041OpenapiSlurmdbdJobsRespJobsInnerWckey as V0041OpenapiSlurmdbdJobsRespJobsInnerWckey,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner import (
    V0041OpenapiSlurmdbdQosRespQosInner as V0041OpenapiSlurmdbdQosRespQosInner,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimits as V0041OpenapiSlurmdbdQosRespQosInnerLimits,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_factor import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsFactor as V0041OpenapiSlurmdbdQosRespQosInnerLimitsFactor,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMax as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMax,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_accruing import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxAccruing as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxAccruing,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_accruing_per import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxAccruingPer as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxAccruingPer,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_accruing_per_account import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxAccruingPerAccount as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxAccruingPerAccount,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_accruing_per_user import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxAccruingPerUser as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxAccruingPerUser,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_active_jobs import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxActiveJobs as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxActiveJobs,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_active_jobs_accruing import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxActiveJobsAccruing as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxActiveJobsAccruing,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_active_jobs_count import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxActiveJobsCount as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxActiveJobsCount,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_jobs import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobs as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobs,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_jobs_active_jobs import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobsActiveJobs as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobsActiveJobs,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_jobs_active_jobs_per import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobsActiveJobsPer as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobsActiveJobsPer,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_jobs_active_jobs_per_account import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobsActiveJobsPerAccount as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobsActiveJobsPerAccount,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_jobs_active_jobs_per_user import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobsActiveJobsPerUser as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobsActiveJobsPerUser,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_jobs_per import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobsPer as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobsPer,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_jobs_per_account import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobsPerAccount as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobsPerAccount,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_jobs_per_user import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobsPerUser as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxJobsPerUser,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_tres import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxTres as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxTres,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_tres_minutes import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxTresMinutes as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxTresMinutes,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_tres_minutes_per import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxTresMinutesPer as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxTresMinutesPer,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_tres_per import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxTresPer as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxTresPer,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_wall_clock import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxWallClock as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxWallClock,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_wall_clock_per import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxWallClockPer as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxWallClockPer,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_wall_clock_per_job import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxWallClockPerJob as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxWallClockPerJob,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_max_wall_clock_per_qos import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxWallClockPerQos as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMaxWallClockPerQos,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_min import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMin as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMin,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_min_priority_threshold import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMinPriorityThreshold as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMinPriorityThreshold,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_min_tres import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMinTres as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMinTres,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_limits_min_tres_per import (
    V0041OpenapiSlurmdbdQosRespQosInnerLimitsMinTresPer as V0041OpenapiSlurmdbdQosRespQosInnerLimitsMinTresPer,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_preempt import (
    V0041OpenapiSlurmdbdQosRespQosInnerPreempt as V0041OpenapiSlurmdbdQosRespQosInnerPreempt,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_preempt_exempt_time import (
    V0041OpenapiSlurmdbdQosRespQosInnerPreemptExemptTime as V0041OpenapiSlurmdbdQosRespQosInnerPreemptExemptTime,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_priority import (
    V0041OpenapiSlurmdbdQosRespQosInnerPriority as V0041OpenapiSlurmdbdQosRespQosInnerPriority,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_usage_factor import (
    V0041OpenapiSlurmdbdQosRespQosInnerUsageFactor as V0041OpenapiSlurmdbdQosRespQosInnerUsageFactor,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_qos_resp_qos_inner_usage_threshold import (
    V0041OpenapiSlurmdbdQosRespQosInnerUsageThreshold as V0041OpenapiSlurmdbdQosRespQosInnerUsageThreshold,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_stats_resp_statistics import (
    V0041OpenapiSlurmdbdStatsRespStatistics as V0041OpenapiSlurmdbdStatsRespStatistics,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_stats_resp_statistics_rpcs_inner import (
    V0041OpenapiSlurmdbdStatsRespStatisticsRPCsInner as V0041OpenapiSlurmdbdStatsRespStatisticsRPCsInner,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_stats_resp_statistics_rpcs_inner_time import (
    V0041OpenapiSlurmdbdStatsRespStatisticsRPCsInnerTime as V0041OpenapiSlurmdbdStatsRespStatisticsRPCsInnerTime,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_stats_resp_statistics_rollups import (
    V0041OpenapiSlurmdbdStatsRespStatisticsRollups as V0041OpenapiSlurmdbdStatsRespStatisticsRollups,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_stats_resp_statistics_rollups_daily import (
    V0041OpenapiSlurmdbdStatsRespStatisticsRollupsDaily as V0041OpenapiSlurmdbdStatsRespStatisticsRollupsDaily,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_stats_resp_statistics_rollups_daily_duration import (
    V0041OpenapiSlurmdbdStatsRespStatisticsRollupsDailyDuration as V0041OpenapiSlurmdbdStatsRespStatisticsRollupsDailyDuration,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_stats_resp_statistics_rollups_hourly import (
    V0041OpenapiSlurmdbdStatsRespStatisticsRollupsHourly as V0041OpenapiSlurmdbdStatsRespStatisticsRollupsHourly,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_stats_resp_statistics_rollups_hourly_duration import (
    V0041OpenapiSlurmdbdStatsRespStatisticsRollupsHourlyDuration as V0041OpenapiSlurmdbdStatsRespStatisticsRollupsHourlyDuration,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_stats_resp_statistics_rollups_monthly import (
    V0041OpenapiSlurmdbdStatsRespStatisticsRollupsMonthly as V0041OpenapiSlurmdbdStatsRespStatisticsRollupsMonthly,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_stats_resp_statistics_rollups_monthly_duration import (
    V0041OpenapiSlurmdbdStatsRespStatisticsRollupsMonthlyDuration as V0041OpenapiSlurmdbdStatsRespStatisticsRollupsMonthlyDuration,
)
from slurpy.v0041.models.v0041_openapi_slurmdbd_stats_resp_statistics_users_inner import (
    V0041OpenapiSlurmdbdStatsRespStatisticsUsersInner as V0041OpenapiSlurmdbdStatsRespStatisticsUsersInner,
)
from slurpy.v0041.models.v0041_openapi_tres_resp_tres_inner import (
    V0041OpenapiTresRespTRESInner as V0041OpenapiTresRespTRESInner,
)
from slurpy.v0041.models.v0041_openapi_users_add_cond_resp_association_condition import (
    V0041OpenapiUsersAddCondRespAssociationCondition as V0041OpenapiUsersAddCondRespAssociationCondition,
)
from slurpy.v0041.models.v0041_openapi_users_add_cond_resp_association_condition_association import (
    V0041OpenapiUsersAddCondRespAssociationConditionAssociation as V0041OpenapiUsersAddCondRespAssociationConditionAssociation,
)
from slurpy.v0041.models.v0041_openapi_users_add_cond_resp_association_condition_association_grpjobs import (
    V0041OpenapiUsersAddCondRespAssociationConditionAssociationGrpjobs as V0041OpenapiUsersAddCondRespAssociationConditionAssociationGrpjobs,
)
from slurpy.v0041.models.v0041_openapi_users_add_cond_resp_association_condition_association_grpjobsaccrue import (
    V0041OpenapiUsersAddCondRespAssociationConditionAssociationGrpjobsaccrue as V0041OpenapiUsersAddCondRespAssociationConditionAssociationGrpjobsaccrue,
)
from slurpy.v0041.models.v0041_openapi_users_add_cond_resp_association_condition_association_grpsubmitjobs import (
    V0041OpenapiUsersAddCondRespAssociationConditionAssociationGrpsubmitjobs as V0041OpenapiUsersAddCondRespAssociationConditionAssociationGrpsubmitjobs,
)
from slurpy.v0041.models.v0041_openapi_users_add_cond_resp_association_condition_association_grpwall import (
    V0041OpenapiUsersAddCondRespAssociationConditionAssociationGrpwall as V0041OpenapiUsersAddCondRespAssociationConditionAssociationGrpwall,
)
from slurpy.v0041.models.v0041_openapi_users_add_cond_resp_association_condition_association_maxjobs import (
    V0041OpenapiUsersAddCondRespAssociationConditionAssociationMaxjobs as V0041OpenapiUsersAddCondRespAssociationConditionAssociationMaxjobs,
)
from slurpy.v0041.models.v0041_openapi_users_add_cond_resp_association_condition_association_maxjobsaccrue import (
    V0041OpenapiUsersAddCondRespAssociationConditionAssociationMaxjobsaccrue as V0041OpenapiUsersAddCondRespAssociationConditionAssociationMaxjobsaccrue,
)
from slurpy.v0041.models.v0041_openapi_users_add_cond_resp_association_condition_association_maxsubmitjobs import (
    V0041OpenapiUsersAddCondRespAssociationConditionAssociationMaxsubmitjobs as V0041OpenapiUsersAddCondRespAssociationConditionAssociationMaxsubmitjobs,
)
from slurpy.v0041.models.v0041_openapi_users_add_cond_resp_association_condition_association_maxwalldurationperjob import (
    V0041OpenapiUsersAddCondRespAssociationConditionAssociationMaxwalldurationperjob as V0041OpenapiUsersAddCondRespAssociationConditionAssociationMaxwalldurationperjob,
)
from slurpy.v0041.models.v0041_openapi_users_add_cond_resp_association_condition_association_minpriothresh import (
    V0041OpenapiUsersAddCondRespAssociationConditionAssociationMinpriothresh as V0041OpenapiUsersAddCondRespAssociationConditionAssociationMinpriothresh,
)
from slurpy.v0041.models.v0041_openapi_users_add_cond_resp_association_condition_association_priority import (
    V0041OpenapiUsersAddCondRespAssociationConditionAssociationPriority as V0041OpenapiUsersAddCondRespAssociationConditionAssociationPriority,
)
from slurpy.v0041.models.v0041_openapi_users_add_cond_resp_user import (
    V0041OpenapiUsersAddCondRespUser as V0041OpenapiUsersAddCondRespUser,
)
from slurpy.v0041.models.v0041_openapi_users_resp_users_inner import (
    V0041OpenapiUsersRespUsersInner as V0041OpenapiUsersRespUsersInner,
)
from slurpy.v0041.models.v0041_openapi_users_resp_users_inner_default import (
    V0041OpenapiUsersRespUsersInnerDefault as V0041OpenapiUsersRespUsersInnerDefault,
)
from slurpy.v0041.models.v0041_openapi_users_resp_users_inner_wckeys_inner import (
    V0041OpenapiUsersRespUsersInnerWckeysInner as V0041OpenapiUsersRespUsersInnerWckeysInner,
)
from slurpy.v0041.models.v0041_openapi_users_resp_users_inner_wckeys_inner_accounting_inner import (
    V0041OpenapiUsersRespUsersInnerWckeysInnerAccountingInner as V0041OpenapiUsersRespUsersInnerWckeysInnerAccountingInner,
)
from slurpy.v0041.models.v0041_openapi_users_resp_users_inner_wckeys_inner_accounting_inner_allocated import (
    V0041OpenapiUsersRespUsersInnerWckeysInnerAccountingInnerAllocated as V0041OpenapiUsersRespUsersInnerWckeysInnerAccountingInnerAllocated,
)
from slurpy.v0041.models.v0041_openapi_users_resp_users_inner_wckeys_inner_accounting_inner_tres import (
    V0041OpenapiUsersRespUsersInnerWckeysInnerAccountingInnerTRES as V0041OpenapiUsersRespUsersInnerWckeysInnerAccountingInnerTRES,
)
from slurpy.v0041.models.v0041_update_node_msg_resume_after import (
    V0041UpdateNodeMsgResumeAfter as V0041UpdateNodeMsgResumeAfter,
)
from slurpy.v0041.models.v0041_update_node_msg_weight import (
    V0041UpdateNodeMsgWeight as V0041UpdateNodeMsgWeight,
)
