# coding: utf-8

"""
Slurm REST API

API to access and control Slurm

The version of the OpenAPI document: Slurm-24.11.6&openapi/slurmdbd&openapi/slurmctld
Contact: sales@schedmd.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from slurpy.v0041.api.slurmdb_api import SlurmdbApi


class TestSlurmdbApi(unittest.TestCase):
    """SlurmdbApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SlurmdbApi()

    def tearDown(self) -> None:
        pass

    def test_delete_account(self) -> None:
        """Test case for delete_account

        Delete account
        """
        pass

    def test_delete_association(self) -> None:
        """Test case for delete_association

        Delete association
        """
        pass

    def test_delete_associations(self) -> None:
        """Test case for delete_associations

        Delete associations
        """
        pass

    def test_delete_cluster(self) -> None:
        """Test case for delete_cluster

        Delete cluster
        """
        pass

    def test_delete_single_qos(self) -> None:
        """Test case for delete_single_qos

        Delete QOS
        """
        pass

    def test_delete_user(self) -> None:
        """Test case for delete_user

        Delete user
        """
        pass

    def test_delete_wckey(self) -> None:
        """Test case for delete_wckey

        Delete wckey
        """
        pass

    def test_get_account(self) -> None:
        """Test case for get_account

        Get account info
        """
        pass

    def test_get_accounts(self) -> None:
        """Test case for get_accounts

        Get account list
        """
        pass

    def test_get_association(self) -> None:
        """Test case for get_association

        Get association info
        """
        pass

    def test_get_associations(self) -> None:
        """Test case for get_associations

        Get association list
        """
        pass

    def test_get_cluster(self) -> None:
        """Test case for get_cluster

        Get cluster info
        """
        pass

    def test_get_clusters(self) -> None:
        """Test case for get_clusters

        Get cluster list
        """
        pass

    def test_get_config(self) -> None:
        """Test case for get_config

        Dump all configuration information
        """
        pass

    def test_get_diag(self) -> None:
        """Test case for get_diag

        Get slurmdb diagnostics
        """
        pass

    def test_get_instance(self) -> None:
        """Test case for get_instance

        Get instance info
        """
        pass

    def test_get_instances(self) -> None:
        """Test case for get_instances

        Get instance list
        """
        pass

    def test_get_job(self) -> None:
        """Test case for get_job

        Get job info
        """
        pass

    def test_get_jobs(self) -> None:
        """Test case for get_jobs

        Get job list
        """
        pass

    def test_get_qos(self) -> None:
        """Test case for get_qos

        Get QOS list
        """
        pass

    def test_get_single_qos(self) -> None:
        """Test case for get_single_qos

        Get QOS info
        """
        pass

    def test_get_tres(self) -> None:
        """Test case for get_tres

        Get TRES info
        """
        pass

    def test_get_user(self) -> None:
        """Test case for get_user

        Get user info
        """
        pass

    def test_get_users(self) -> None:
        """Test case for get_users

        Get user list
        """
        pass

    def test_get_wckey(self) -> None:
        """Test case for get_wckey

        Get wckey info
        """
        pass

    def test_get_wckeys(self) -> None:
        """Test case for get_wckeys

        Get wckey list
        """
        pass

    def test_post_accounts(self) -> None:
        """Test case for post_accounts

        Add/update list of accounts
        """
        pass

    def test_post_accounts_association(self) -> None:
        """Test case for post_accounts_association

        Add accounts with conditional association
        """
        pass

    def test_post_associations(self) -> None:
        """Test case for post_associations

        Set associations info
        """
        pass

    def test_post_clusters(self) -> None:
        """Test case for post_clusters

        Get cluster list
        """
        pass

    def test_post_config(self) -> None:
        """Test case for post_config

        Load all configuration information
        """
        pass

    def test_post_qos(self) -> None:
        """Test case for post_qos

        Add or update QOSs
        """
        pass

    def test_post_tres(self) -> None:
        """Test case for post_tres

        Add TRES
        """
        pass

    def test_post_users(self) -> None:
        """Test case for post_users

        Update users
        """
        pass

    def test_post_users_association(self) -> None:
        """Test case for post_users_association

        Add users with conditional association
        """
        pass

    def test_post_wckeys(self) -> None:
        """Test case for post_wckeys

        Add or update wckeys
        """
        pass


if __name__ == "__main__":
    unittest.main()
