# coding: utf-8

# flake8: noqa
"""
Slurm REST API

API to access and control Slurm

The version of the OpenAPI document: Slurm-24.11.6&openapi/slurmdbd&openapi/slurmctld
Contact: sales@schedmd.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from slurpy.v0040.models.account import Account
from slurpy.v0040.models.account_short import AccountShort
from slurpy.v0040.models.accounting import Accounting
from slurpy.v0040.models.accounts_add_cond import AccountsAddCond
from slurpy.v0040.models.acct_gather_energy import AcctGatherEnergy
from slurpy.v0040.models.assoc import Assoc
from slurpy.v0040.models.assoc_rec_set import AssocRecSet
from slurpy.v0040.models.assoc_shares_obj_wrap import AssocSharesObjWrap
from slurpy.v0040.models.assoc_short import AssocShort
from slurpy.v0040.models.bf_exit_fields import BfExitFields
from slurpy.v0040.models.cluster_rec import ClusterRec
from slurpy.v0040.models.controller_ping import ControllerPing
from slurpy.v0040.models.coord import Coord
from slurpy.v0040.models.cron_entry import CronEntry
from slurpy.v0040.models.float64_no_val import Float64NoVal
from slurpy.v0040.models.instance import Instance
from slurpy.v0040.models.job import Job
from slurpy.v0040.models.job_array_response_msg_entry import JobArrayResponseMsgEntry
from slurpy.v0040.models.job_desc_msg import JobDescMsg
from slurpy.v0040.models.job_info import JobInfo
from slurpy.v0040.models.job_res import JobRes
from slurpy.v0040.models.job_submit_req import JobSubmitReq
from slurpy.v0040.models.job_submit_response_msg import JobSubmitResponseMsg
from slurpy.v0040.models.kill_jobs_msg import KillJobsMsg
from slurpy.v0040.models.kill_jobs_resp_job import KillJobsRespJob
from slurpy.v0040.models.license import License
from slurpy.v0040.models.node import Node
from slurpy.v0040.models.open_api_accounts_add_cond_resp import (
    OpenAPIAccountsAddCondResp,
)
from slurpy.v0040.models.open_api_accounts_add_cond_resp_str import (
    OpenAPIAccountsAddCondRespStr,
)
from slurpy.v0040.models.open_api_accounts_removed_resp import (
    OpenAPIAccountsRemovedResp,
)
from slurpy.v0040.models.open_api_accounts_resp import OpenAPIAccountsResp
from slurpy.v0040.models.open_api_assocs_removed_resp import OpenAPIAssocsRemovedResp
from slurpy.v0040.models.open_api_assocs_resp import OpenAPIAssocsResp
from slurpy.v0040.models.open_api_clusters_removed_resp import (
    OpenAPIClustersRemovedResp,
)
from slurpy.v0040.models.open_api_clusters_resp import OpenAPIClustersResp
from slurpy.v0040.models.open_api_diag_resp import OpenAPIDiagResp
from slurpy.v0040.models.open_api_error import OpenAPIError
from slurpy.v0040.models.open_api_instances_resp import OpenAPIInstancesResp
from slurpy.v0040.models.open_api_job_info_resp import OpenAPIJobInfoResp
from slurpy.v0040.models.open_api_job_post_response import OpenAPIJobPostResponse
from slurpy.v0040.models.open_api_job_submit_response import OpenAPIJobSubmitResponse
from slurpy.v0040.models.open_api_kill_jobs_resp import OpenAPIKillJobsResp
from slurpy.v0040.models.open_api_licenses_resp import OpenAPILicensesResp
from slurpy.v0040.models.open_api_meta import OpenAPIMeta
from slurpy.v0040.models.open_api_nodes_resp import OpenAPINodesResp
from slurpy.v0040.models.open_api_partition_resp import OpenAPIPartitionResp
from slurpy.v0040.models.open_api_ping_array_resp import OpenAPIPingArrayResp
from slurpy.v0040.models.open_api_reservation_resp import OpenAPIReservationResp
from slurpy.v0040.models.open_api_resp import OpenAPIResp
from slurpy.v0040.models.open_api_shares_resp import OpenAPISharesResp
from slurpy.v0040.models.open_api_slurmdbd_config_resp import OpenAPISlurmdbdConfigResp
from slurpy.v0040.models.open_api_slurmdbd_jobs_resp import OpenAPISlurmdbdJobsResp
from slurpy.v0040.models.open_api_slurmdbd_qos_removed_resp import (
    OpenAPISlurmdbdQosRemovedResp,
)
from slurpy.v0040.models.open_api_slurmdbd_qos_resp import OpenAPISlurmdbdQosResp
from slurpy.v0040.models.open_api_slurmdbd_stats_resp import OpenAPISlurmdbdStatsResp
from slurpy.v0040.models.open_api_tres_resp import OpenAPITresResp
from slurpy.v0040.models.open_api_users_add_cond_resp import OpenAPIUsersAddCondResp
from slurpy.v0040.models.open_api_users_add_cond_resp_str import (
    OpenAPIUsersAddCondRespStr,
)
from slurpy.v0040.models.open_api_users_resp import OpenAPIUsersResp
from slurpy.v0040.models.open_api_warning import OpenAPIWarning
from slurpy.v0040.models.open_api_wckey_removed_resp import OpenAPIWckeyRemovedResp
from slurpy.v0040.models.open_api_wckey_resp import OpenAPIWckeyResp
from slurpy.v0040.models.partition_info import PartitionInfo
from slurpy.v0040.models.process_exit_code_verbose import ProcessExitCodeVerbose
from slurpy.v0040.models.qos import Qos
from slurpy.v0040.models.reservation_core_spec import ReservationCoreSpec
from slurpy.v0040.models.reservation_info import ReservationInfo
from slurpy.v0040.models.schedule_exit_fields import ScheduleExitFields
from slurpy.v0040.models.shares_float128_tres import SharesFloat128Tres
from slurpy.v0040.models.shares_resp_msg import SharesRespMsg
from slurpy.v0040.models.shares_uint64_tres import SharesUint64Tres
from slurpy.v0040.models.stats_msg import StatsMsg
from slurpy.v0040.models.stats_rec import StatsRec
from slurpy.v0040.models.stats_rpc import StatsRpc
from slurpy.v0040.models.stats_user import StatsUser
from slurpy.v0040.models.step import Step
from slurpy.v0040.models.tres import Tres
from slurpy.v0040.models.uint16_no_val import Uint16NoVal
from slurpy.v0040.models.uint32_no_val import Uint32NoVal
from slurpy.v0040.models.uint64_no_val import Uint64NoVal
from slurpy.v0040.models.update_node_msg import UpdateNodeMsg
from slurpy.v0040.models.user import User
from slurpy.v0040.models.user_short import UserShort
from slurpy.v0040.models.users_add_cond import UsersAddCond
from slurpy.v0040.models.v0040_accounting_allocated import V0040AccountingAllocated
from slurpy.v0040.models.v0040_assoc_default import V0040AssocDefault
from slurpy.v0040.models.v0040_assoc_max import V0040AssocMax
from slurpy.v0040.models.v0040_assoc_max_jobs import V0040AssocMaxJobs
from slurpy.v0040.models.v0040_assoc_max_jobs_per import V0040AssocMaxJobsPer
from slurpy.v0040.models.v0040_assoc_max_per import V0040AssocMaxPer
from slurpy.v0040.models.v0040_assoc_max_per_account import V0040AssocMaxPerAccount
from slurpy.v0040.models.v0040_assoc_max_tres import V0040AssocMaxTres
from slurpy.v0040.models.v0040_assoc_max_tres_group import V0040AssocMaxTresGroup
from slurpy.v0040.models.v0040_assoc_max_tres_minutes import V0040AssocMaxTresMinutes
from slurpy.v0040.models.v0040_assoc_max_tres_per import V0040AssocMaxTresPer
from slurpy.v0040.models.v0040_assoc_min import V0040AssocMin
from slurpy.v0040.models.v0040_assoc_shares_obj_wrap_fairshare import (
    V0040AssocSharesObjWrapFairshare,
)
from slurpy.v0040.models.v0040_assoc_shares_obj_wrap_tres import (
    V0040AssocSharesObjWrapTres,
)
from slurpy.v0040.models.v0040_cluster_rec_associations import (
    V0040ClusterRecAssociations,
)
from slurpy.v0040.models.v0040_cluster_rec_controller import V0040ClusterRecController
from slurpy.v0040.models.v0040_cron_entry_line import V0040CronEntryLine
from slurpy.v0040.models.v0040_instance_time import V0040InstanceTime
from slurpy.v0040.models.v0040_job_array import V0040JobArray
from slurpy.v0040.models.v0040_job_array_limits import V0040JobArrayLimits
from slurpy.v0040.models.v0040_job_array_limits_max import V0040JobArrayLimitsMax
from slurpy.v0040.models.v0040_job_array_limits_max_running import (
    V0040JobArrayLimitsMaxRunning,
)
from slurpy.v0040.models.v0040_job_comment import V0040JobComment
from slurpy.v0040.models.v0040_job_desc_msg_rlimits import V0040JobDescMsgRlimits
from slurpy.v0040.models.v0040_job_het import V0040JobHet
from slurpy.v0040.models.v0040_job_info_power import V0040JobInfoPower
from slurpy.v0040.models.v0040_job_mcs import V0040JobMcs
from slurpy.v0040.models.v0040_job_required import V0040JobRequired
from slurpy.v0040.models.v0040_job_reservation import V0040JobReservation
from slurpy.v0040.models.v0040_job_state import V0040JobState
from slurpy.v0040.models.v0040_job_time import V0040JobTime
from slurpy.v0040.models.v0040_job_time_system import V0040JobTimeSystem
from slurpy.v0040.models.v0040_job_time_total import V0040JobTimeTotal
from slurpy.v0040.models.v0040_job_time_user import V0040JobTimeUser
from slurpy.v0040.models.v0040_job_tres import V0040JobTres
from slurpy.v0040.models.v0040_kill_jobs_resp_job_error import V0040KillJobsRespJobError
from slurpy.v0040.models.v0040_kill_jobs_resp_job_federation import (
    V0040KillJobsRespJobFederation,
)
from slurpy.v0040.models.v0040_openapi_meta_client import V0040OpenapiMetaClient
from slurpy.v0040.models.v0040_openapi_meta_plugin import V0040OpenapiMetaPlugin
from slurpy.v0040.models.v0040_openapi_meta_slurm import V0040OpenapiMetaSlurm
from slurpy.v0040.models.v0040_openapi_meta_slurm_version import (
    V0040OpenapiMetaSlurmVersion,
)
from slurpy.v0040.models.v0040_partition_info_accounts import V0040PartitionInfoAccounts
from slurpy.v0040.models.v0040_partition_info_cpus import V0040PartitionInfoCpus
from slurpy.v0040.models.v0040_partition_info_defaults import V0040PartitionInfoDefaults
from slurpy.v0040.models.v0040_partition_info_groups import V0040PartitionInfoGroups
from slurpy.v0040.models.v0040_partition_info_maximums import V0040PartitionInfoMaximums
from slurpy.v0040.models.v0040_partition_info_maximums_oversubscribe import (
    V0040PartitionInfoMaximumsOversubscribe,
)
from slurpy.v0040.models.v0040_partition_info_minimums import V0040PartitionInfoMinimums
from slurpy.v0040.models.v0040_partition_info_nodes import V0040PartitionInfoNodes
from slurpy.v0040.models.v0040_partition_info_partition import (
    V0040PartitionInfoPartition,
)
from slurpy.v0040.models.v0040_partition_info_priority import V0040PartitionInfoPriority
from slurpy.v0040.models.v0040_partition_info_qos import V0040PartitionInfoQos
from slurpy.v0040.models.v0040_partition_info_timeouts import V0040PartitionInfoTimeouts
from slurpy.v0040.models.v0040_partition_info_tres import V0040PartitionInfoTres
from slurpy.v0040.models.v0040_process_exit_code_verbose_signal import (
    V0040ProcessExitCodeVerboseSignal,
)
from slurpy.v0040.models.v0040_qos_limits import V0040QosLimits
from slurpy.v0040.models.v0040_qos_limits_max import V0040QosLimitsMax
from slurpy.v0040.models.v0040_qos_limits_max_active_jobs import (
    V0040QosLimitsMaxActiveJobs,
)
from slurpy.v0040.models.v0040_qos_limits_max_jobs import V0040QosLimitsMaxJobs
from slurpy.v0040.models.v0040_qos_limits_max_jobs_active_jobs import (
    V0040QosLimitsMaxJobsActiveJobs,
)
from slurpy.v0040.models.v0040_qos_limits_max_jobs_active_jobs_per import (
    V0040QosLimitsMaxJobsActiveJobsPer,
)
from slurpy.v0040.models.v0040_qos_limits_max_tres import V0040QosLimitsMaxTres
from slurpy.v0040.models.v0040_qos_limits_max_tres_minutes import (
    V0040QosLimitsMaxTresMinutes,
)
from slurpy.v0040.models.v0040_qos_limits_max_tres_minutes_per import (
    V0040QosLimitsMaxTresMinutesPer,
)
from slurpy.v0040.models.v0040_qos_limits_max_tres_per import V0040QosLimitsMaxTresPer
from slurpy.v0040.models.v0040_qos_limits_max_wall_clock import (
    V0040QosLimitsMaxWallClock,
)
from slurpy.v0040.models.v0040_qos_limits_max_wall_clock_per import (
    V0040QosLimitsMaxWallClockPer,
)
from slurpy.v0040.models.v0040_qos_limits_min import V0040QosLimitsMin
from slurpy.v0040.models.v0040_qos_limits_min_tres import V0040QosLimitsMinTres
from slurpy.v0040.models.v0040_qos_limits_min_tres_per import V0040QosLimitsMinTresPer
from slurpy.v0040.models.v0040_qos_preempt import V0040QosPreempt
from slurpy.v0040.models.v0040_reservation_info_purge_completed import (
    V0040ReservationInfoPurgeCompleted,
)
from slurpy.v0040.models.v0040_rollup_stats_inner import V0040RollupStatsInner
from slurpy.v0040.models.v0040_stats_msg_rpcs_by_type_inner import (
    V0040StatsMsgRpcsByTypeInner,
)
from slurpy.v0040.models.v0040_stats_msg_rpcs_by_user_inner import (
    V0040StatsMsgRpcsByUserInner,
)
from slurpy.v0040.models.v0040_stats_rpc_time import V0040StatsRpcTime
from slurpy.v0040.models.v0040_step_cpu import V0040StepCPU
from slurpy.v0040.models.v0040_step_cpu_requested_frequency import (
    V0040StepCPURequestedFrequency,
)
from slurpy.v0040.models.v0040_step_nodes import V0040StepNodes
from slurpy.v0040.models.v0040_step_statistics import V0040StepStatistics
from slurpy.v0040.models.v0040_step_statistics_cpu import V0040StepStatisticsCPU
from slurpy.v0040.models.v0040_step_statistics_energy import V0040StepStatisticsEnergy
from slurpy.v0040.models.v0040_step_step import V0040StepStep
from slurpy.v0040.models.v0040_step_task import V0040StepTask
from slurpy.v0040.models.v0040_step_tasks import V0040StepTasks
from slurpy.v0040.models.v0040_step_time import V0040StepTime
from slurpy.v0040.models.v0040_step_time_system import V0040StepTimeSystem
from slurpy.v0040.models.v0040_step_time_total import V0040StepTimeTotal
from slurpy.v0040.models.v0040_step_time_user import V0040StepTimeUser
from slurpy.v0040.models.v0040_step_tres import V0040StepTres
from slurpy.v0040.models.v0040_step_tres_consumed import V0040StepTresConsumed
from slurpy.v0040.models.v0040_step_tres_requested import V0040StepTresRequested
from slurpy.v0040.models.v0040_user_default import V0040UserDefault
from slurpy.v0040.models.wckey import Wckey
from slurpy.v0040.models.wckey_tag_struct import WckeyTagStruct
